export type ExamBlueprintPolicyFamily =
  | 'EXAM_BLUEPRINT_CREATION'
  | 'EXAM_BLUEPRINT_APPROVAL'
  | 'EXAM_DRAFT_GENERATION'
  | 'QUESTION_SELECTION';

export const EXAM_BLUEPRINT_POLICY_FAMILIES: readonly ExamBlueprintPolicyFamily[] = [
  'EXAM_BLUEPRINT_CREATION',
  'EXAM_BLUEPRINT_APPROVAL',
  'EXAM_DRAFT_GENERATION',
  'QUESTION_SELECTION',
] as const;
