export type QuestionBankPolicyFamily =
  | 'QUESTION_DRAFT_CREATION'
  | 'QUESTION_APPROVAL'
  | 'QUESTION_EXAM_USAGE'
  | 'QUESTION_ORAL_USAGE'
  | 'QUESTION_AI_ASSISTED_DRAFT'
  | 'QUESTION_DEEN_CONTENT_AUTHORITY'
  | 'QUESTION_CURRICULUM_VALIDITY'
  | 'QUESTION_CONTENT_SAFETY_REVIEW';

export const QUESTION_BANK_POLICY_FAMILIES: readonly QuestionBankPolicyFamily[] = [
  'QUESTION_DRAFT_CREATION',
  'QUESTION_APPROVAL',
  'QUESTION_EXAM_USAGE',
  'QUESTION_ORAL_USAGE',
  'QUESTION_AI_ASSISTED_DRAFT',
  'QUESTION_DEEN_CONTENT_AUTHORITY',
  'QUESTION_CURRICULUM_VALIDITY',
  'QUESTION_CONTENT_SAFETY_REVIEW',
] as const;
