export const SCHEMA_VERSION = 1;

export const STATES = Object.freeze({
  PREFLIGHT: 'PREFLIGHT',
  IMPLEMENTING: 'IMPLEMENTING',
  ERROR_REPAIR: 'ERROR_REPAIR',
  TODO_VERIFICATION: 'TODO_VERIFICATION',
  PRE_COMMIT_VERIFICATION: 'PRE_COMMIT_VERIFICATION',
  STAGING: 'STAGING',
  IMPLEMENTATION_COMMITTED: 'IMPLEMENTATION_COMMITTED',
  POST_COMMIT_VERIFICATION: 'POST_COMMIT_VERIFICATION',
  ACCOUNTABILITY_COMMITTED: 'ACCOUNTABILITY_COMMITTED',
  FINAL_REPOSITORY_PROOF: 'FINAL_REPOSITORY_PROOF',
  ACCEPTED_READY: 'ACCEPTED_READY',
  BLOCKED: 'BLOCKED',
});

export const NORMAL_PATH = [
  STATES.PREFLIGHT,
  STATES.IMPLEMENTING,
  STATES.TODO_VERIFICATION,
  STATES.PRE_COMMIT_VERIFICATION,
  STATES.STAGING,
  STATES.IMPLEMENTATION_COMMITTED,
  STATES.POST_COMMIT_VERIFICATION,
  STATES.ACCOUNTABILITY_COMMITTED,
  STATES.FINAL_REPOSITORY_PROOF,
  STATES.ACCEPTED_READY,
];

export const EXECUTABLE_STATES = new Set([
  STATES.PREFLIGHT,
  STATES.IMPLEMENTING,
  STATES.ERROR_REPAIR,
  STATES.TODO_VERIFICATION,
  STATES.PRE_COMMIT_VERIFICATION,
  STATES.STAGING,
  STATES.IMPLEMENTATION_COMMITTED,
  STATES.POST_COMMIT_VERIFICATION,
  STATES.ACCOUNTABILITY_COMMITTED,
  STATES.FINAL_REPOSITORY_PROOF,
]);

export const TERMINAL_STATES = new Set([STATES.ACCEPTED_READY, STATES.BLOCKED]);

export const TRANSITIONS = Object.freeze({
  [STATES.PREFLIGHT]: [STATES.IMPLEMENTING, STATES.ERROR_REPAIR],
  [STATES.IMPLEMENTING]: [STATES.TODO_VERIFICATION, STATES.ERROR_REPAIR],
  [STATES.ERROR_REPAIR]: [STATES.TODO_VERIFICATION, STATES.ERROR_REPAIR],
  [STATES.TODO_VERIFICATION]: [STATES.PRE_COMMIT_VERIFICATION, STATES.ERROR_REPAIR],
  [STATES.PRE_COMMIT_VERIFICATION]: [STATES.STAGING, STATES.ERROR_REPAIR],
  [STATES.STAGING]: [STATES.IMPLEMENTATION_COMMITTED, STATES.ERROR_REPAIR],
  [STATES.IMPLEMENTATION_COMMITTED]: [STATES.POST_COMMIT_VERIFICATION, STATES.ERROR_REPAIR],
  [STATES.POST_COMMIT_VERIFICATION]: [STATES.ACCOUNTABILITY_COMMITTED, STATES.ERROR_REPAIR],
  [STATES.ACCOUNTABILITY_COMMITTED]: [STATES.FINAL_REPOSITORY_PROOF, STATES.ERROR_REPAIR],
  [STATES.FINAL_REPOSITORY_PROOF]: [STATES.ACCEPTED_READY, STATES.BLOCKED, STATES.ERROR_REPAIR],
  [STATES.ACCEPTED_READY]: [],
  [STATES.BLOCKED]: [],
});

export const EXIT_CODES = Object.freeze({
  OK: 0,
  ERROR_REPAIR_LOCKED: 10,
  MANIFEST_INVALID: 11,
  EVIDENCE_INTEGRITY_FAILURE: 12,
  WORKSPACE_SCOPE_VIOLATION: 13,
  TEST_INVENTORY_REGRESSION: 14,
  COMMIT_ORDER_VIOLATION: 15,
  COMMAND_TIMEOUT: 16,
  FINALIZATION_NOT_PERMITTED: 17,
  EXTERNAL_BLOCKER: 18,
});

export const LEDGER_SCHEMA_VERSION = 1;

export const GATE_TYPES = Object.freeze({
  COMMAND: 'command',
  TEST_INVENTORY: 'test_inventory',
  TEST_INTEGRITY: 'test_integrity',
  WORKSPACE: 'workspace',
  SCAN: 'scan',
  COMMIT: 'commit',
  ACCOUNTABILITY: 'accountability',
  FINAL_REPOSITORY: 'final_repository',
});

export const WARNING_PATTERNS = [
  'The system cannot find the path specified',
  'backend/backend',
  'backend\\backend',
  'invalid import',
  'duplicate key',
  'Unhandled Error',
  'Unhandled Rejection',
  'No test files found',
];
