import type { SubjectSeed } from '../subjectTopicMapContracts';

export const cambridgeSubjectSeeds: SubjectSeed[] = [
  {
    subjectId: 'cambridge_mathematics',
    name: 'Mathematics',
    aliases: ['math', 'maths', 'arithmetic', 'algebra', 'geometry', 'calculus', 'numeracy'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_english',
    name: 'English',
    aliases: ['english language', 'ela', 'language arts', 'literacy', 'reading', 'writing', 'grammar'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_science',
    name: 'Science',
    aliases: ['general science', 'natural science', 'sciences'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_ict',
    name: 'ICT',
    aliases: ['information technology', 'computing', 'computer science', 'coding', 'programming', 'digital literacy'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_global_perspectives',
    name: 'Global Perspectives',
    aliases: ['global studies', 'world studies', 'global awareness', 'international studies'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_literature',
    name: 'Literature',
    aliases: ['english literature', 'literary studies', 'poetry', 'prose', 'drama'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_geography',
    name: 'Geography',
    aliases: ['geog', 'physical geography', 'human geography', 'environmental studies'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_history',
    name: 'History',
    aliases: ['world history', 'ancient history', 'modern history', 'historical studies'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_business',
    name: 'Business',
    aliases: ['business studies', 'commerce', 'entrepreneurship', 'business management'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_chemistry',
    name: 'Chemistry',
    aliases: ['chem', 'chemical science'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_biology',
    name: 'Biology',
    aliases: ['bio', 'life science', 'biological science'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_physics',
    name: 'Physics',
    aliases: ['phys', 'physical science'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_statistics',
    name: 'Statistics',
    aliases: ['stats', 'data analysis', 'probability'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_kiswahili',
    name: 'Kiswahili',
    aliases: ['swahili', 'kiswahili language', 'lugha ya kiswahili'],
    category: 'academic',
    curriculumTrack: 'cambridge_academic',
  },
  {
    subjectId: 'cambridge_islamic_religious_education',
    name: 'Islamic Religious Education',
    aliases: ['ire', 'islamic studies', 'religious education', 'islamic knowledge'],
    category: 'mixed',
    curriculumTrack: 'mixed_academic_deen',
  },
];
