import type { TopicSeed } from '../subjectTopicMapContracts';

export const cambridgeTopicSeeds: TopicSeed[] = [
  // ─── Mathematics ───
  {
    topicId: 'math_fractions',
    subjectId: 'cambridge_mathematics',
    title: 'Fractions',
    aliases: ['fractions basics', 'proper fractions', 'improper fractions', 'mixed numbers'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand what a fraction represents', 'Identify proper and improper fractions', 'Convert between mixed numbers and improper fractions'],
    prerequisites: ['basic division', 'multiplication tables'],
    commonMistakes: ['Adding numerators and denominators separately', 'Confusing numerator and denominator', 'Not simplifying final answer'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'math_decimals',
    subjectId: 'cambridge_mathematics',
    title: 'Decimals',
    aliases: ['decimal numbers', 'decimal places', 'decimal fractions'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand decimal place value', 'Convert between fractions and decimals', 'Compare and order decimals'],
    prerequisites: ['fractions basics', 'place value'],
    commonMistakes: ['Misaligning decimal points when adding', 'Dropping trailing zeros incorrectly', 'Confusing tenths and hundredths'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'math_percentages',
    subjectId: 'cambridge_mathematics',
    title: 'Percentages',
    aliases: ['percent', 'percentage of a number', 'percentage change'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Understand percentage as a fraction out of 100', 'Calculate percentage of a quantity', 'Find percentage increase and decrease'],
    prerequisites: ['fractions', 'decimals'],
    commonMistakes: ['Forgetting to divide by 100', 'Adding percentages incorrectly', 'Confusing percentage points with percent change'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'math_algebra_basics',
    subjectId: 'cambridge_mathematics',
    title: 'Algebra Basics',
    aliases: ['algebra', 'introduction to algebra', 'basic algebra', 'algebraic expressions'],
    gradeBands: ['Year 6', 'Key Stage 3', 'Key Stage 4'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand variables and constants', 'Simplify algebraic expressions', 'Solve simple linear equations'],
    prerequisites: ['basic arithmetic', 'order of operations'],
    commonMistakes: ['Confusing variables as multiplication', 'Forgetting to distribute negative signs', 'Mixing up coefficients and exponents'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'math_equations',
    subjectId: 'cambridge_mathematics',
    title: 'Equations',
    aliases: ['solving equations', 'linear equations', 'simple equations'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Solve one-step and two-step equations', 'Check solutions by substitution', 'Set up equations from word problems'],
    prerequisites: ['algebra basics', 'basic operations'],
    commonMistakes: ['Performing operation on only one side', 'Sign errors when moving terms', 'Forgetting to check the solution'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'math_ratio',
    subjectId: 'cambridge_mathematics',
    title: 'Ratio',
    aliases: ['ratios', 'proportion', 'rate'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Understand ratio as a comparison', 'Simplify ratios', 'Solve problems using ratios'],
    prerequisites: ['fractions', 'division'],
    commonMistakes: ['Writing ratio in wrong order', 'Not simplifying the ratio', 'Confusing ratio with fraction'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── English ───
  {
    topicId: 'english_grammar',
    subjectId: 'cambridge_english',
    title: 'Grammar',
    aliases: ['grammar basics', 'parts of speech', 'sentence structure', 'punctuation'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify parts of speech', 'Use correct punctuation', 'Construct complete sentences'],
    prerequisites: ['basic reading'],
    commonMistakes: ['Subject-verb agreement errors', 'Run-on sentences', 'Misplacing apostrophes'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'english_writing',
    subjectId: 'cambridge_english',
    title: 'Writing',
    aliases: ['essay writing', 'composition', 'creative writing', 'report writing'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Plan and structure a written piece', 'Use paragraphs effectively', 'Develop a clear argument or narrative'],
    prerequisites: ['grammar basics', 'vocabulary building'],
    commonMistakes: ['Lack of paragraph structure', 'Repetitive vocabulary', 'Off-topic content'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'english_comprehension',
    subjectId: 'cambridge_english',
    title: 'Comprehension',
    aliases: ['reading comprehension', 'understanding text', 'inference'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify main ideas in a text', 'Make inferences from text', 'Answer questions based on reading'],
    prerequisites: ['basic reading fluency'],
    commonMistakes: ['Copying text without understanding', 'Missing implied meaning', 'Not using evidence from text'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'english_vocabulary',
    subjectId: 'cambridge_english',
    title: 'Vocabulary',
    aliases: ['words', 'word meanings', 'synonyms', 'antonyms'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner'],
    learningObjectives: ['Learn new words and their meanings', 'Use context clues', 'Expand active vocabulary'],
    prerequisites: ['basic reading'],
    commonMistakes: ['Confusing similar sounding words', 'Using words in wrong context', 'Overusing simple words'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Science ───
  {
    topicId: 'science_forces',
    subjectId: 'cambridge_science',
    title: 'Forces',
    aliases: ['forces and motion', 'push and pull', 'gravity', 'friction'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Key Stage 2'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify different types of forces', 'Understand how forces affect motion', 'Measure forces using newton meters'],
    prerequisites: ['basic understanding of motion'],
    commonMistakes: ['Thinking no motion means no force', 'Confusing mass and weight', 'Forgetting friction always opposes motion'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'science_energy',
    subjectId: 'cambridge_science',
    title: 'Energy',
    aliases: ['energy forms', 'energy transfer', 'renewable energy', 'electricity'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Identify different forms of energy', 'Understand energy transfer', 'Recognize renewable and non-renewable sources'],
    prerequisites: ['basic science vocabulary'],
    commonMistakes: ['Confusing energy and force', 'Thinking energy is created not transferred', 'Misunderstanding conservation of energy'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'science_living_things',
    subjectId: 'cambridge_science',
    title: 'Living Things',
    aliases: ['organisms', 'classification', 'habitats', 'life processes'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Key Stage 2'],
    levels: ['beginner'],
    learningObjectives: ['Identify characteristics of living things', 'Classify organisms into groups', 'Understand basic habitats'],
    prerequisites: [],
    commonMistakes: ['Thinking non-moving things are not alive', 'Confusing habitat with ecosystem', 'Misclassifying common animals'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'science_materials',
    subjectId: 'cambridge_science',
    title: 'Materials',
    aliases: ['properties of materials', 'matter', 'states of matter', 'solids liquids gases'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4', 'Year 5', 'Key Stage 2'],
    levels: ['beginner'],
    learningObjectives: ['Identify different materials', 'Describe properties of materials', 'Understand states of matter'],
    prerequisites: [],
    commonMistakes: ['Thinking all solids are hard', 'Confusing melting and dissolving', 'Misidentifying gases as not matter'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'science_scientific_method',
    subjectId: 'cambridge_science',
    title: 'Scientific Method',
    aliases: ['investigation', 'experiment', 'hypothesis', 'fair test'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand steps of scientific investigation', 'Formulate a hypothesis', 'Conduct a fair test'],
    prerequisites: ['basic science vocabulary'],
    commonMistakes: ['Changing multiple variables at once','Confusing hypothesis with prediction', 'Not recording observations properly'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Biology ───
  {
    topicId: 'biology_cells',
    subjectId: 'cambridge_biology',
    title: 'Cells',
    aliases: ['cell structure', 'plant cells', 'animal cells', 'basic unit of life'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Identify parts of a cell', 'Distinguish between plant and animal cells', 'Understand cell function basics'],
    prerequisites: ['basic biology vocabulary'],
    commonMistakes: ['Thinking all cells are the same', 'Confusing mitochondria and chloroplasts', 'Forgetting cell wall is only in plants'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'biology_human_body',
    subjectId: 'cambridge_biology',
    title: 'Human Body',
    aliases: ['body systems', 'digestive system', 'circulatory system', 'respiratory system', 'skeleton'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify major body systems', 'Describe basic functions of organs', 'Understand how body systems work together'],
    prerequisites: ['basic biology vocabulary'],
    commonMistakes: ['Confusing function of different organs', 'Thinking the heart pumps blood for one circuit only', 'Forgetting that systems are interconnected'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'biology_plants',
    subjectId: 'cambridge_biology',
    title: 'Plants',
    aliases: ['plant biology', 'photosynthesis', 'plant growth', 'parts of a plant'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify parts of a plant', 'Understand photosynthesis basics', 'Know what plants need to grow'],
    prerequisites: ['basic biology vocabulary'],
    commonMistakes: ['Thinking plants eat soil for food', 'Confusing respiration and photosynthesis', 'Forgetting plants need oxygen too'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'biology_ecosystems',
    subjectId: 'cambridge_biology',
    title: 'Ecosystems',
    aliases: ['habitats', 'food chains', 'food webs', 'environment', 'biodiversity'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Understand food chains and webs', 'Identify producers, consumers, decomposers', 'Recognize human impact on ecosystems'],
    prerequisites: ['living things', 'basic biology'],
    commonMistakes: ['Putting arrows the wrong way in food chains','Thinking decomposers are not important', 'Confusing habitat with ecosystem'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Chemistry ───
  {
    topicId: 'chemistry_atoms',
    subjectId: 'cambridge_chemistry',
    title: 'Atoms',
    aliases: ['atomic structure', 'elements', 'protons neutrons electrons'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Understand atomic structure', 'Identify protons, neutrons, electrons', 'Read the periodic table basics'],
    prerequisites: ['basic chemistry vocabulary', 'matter'],
    commonMistakes: ['Thinking atoms are visible', 'Confusing atomic number and mass number', 'Thinking electrons orbit in fixed paths'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'chemistry_elements',
    subjectId: 'cambridge_chemistry',
    title: 'Elements',
    aliases: ['periodic table', 'chemical elements', 'element symbols'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Identify common elements', 'Understand periodic table organization', 'Recognize element symbols'],
    prerequisites: ['atoms basics'],
    commonMistakes: ['Confusing element symbols with abbreviations','Thinking all elements are naturally occurring', 'Misreading periodic table groups'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'chemistry_mixtures',
    subjectId: 'cambridge_chemistry',
    title: 'Mixtures',
    aliases: ['mixtures and compounds', 'solutions', 'separation techniques'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Distinguish between mixtures and pure substances', 'Understand solutions and solubility', 'Describe separation methods'],
    prerequisites: ['materials', 'elements'],
    commonMistakes: ['Confusing mixtures and compounds','Thinking all mixtures are liquids', 'Forgetting that air is a mixture'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'chemistry_reactions',
    subjectId: 'cambridge_chemistry',
    title: 'Reactions',
    aliases: ['chemical reactions', 'chemical changes', 'reactants and products'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Recognize signs of a chemical reaction', 'Understand reactants and products', 'Simple balanced equations'],
    prerequisites: ['elements', 'atoms'],
    commonMistakes: ['Confusing physical and chemical changes','Forgetting conservation of mass', 'Unbalanced equations'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Physics ───
  {
    topicId: 'physics_motion',
    subjectId: 'cambridge_physics',
    title: 'Motion',
    aliases: ['speed', 'velocity', 'distance-time graphs', 'movement'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Calculate speed from distance and time', 'Interpret distance-time graphs', 'Understand relative motion'],
    prerequisites: ['basic arithmetic', 'forces'],
    commonMistakes: ['Confusing speed and velocity','Thinking constant speed means no forces', 'Misreading graph axes'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'physics_forces',
    subjectId: 'cambridge_physics',
    title: 'Forces (Physics)',
    aliases: ['resultant forces', 'balanced forces', 'unbalanced forces', 'newtons laws'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Understand Newton\'s laws of motion', 'Calculate resultant forces', 'Apply force concepts to real situations'],
    prerequisites: ['science forces basics', 'algebra basics'],
    commonMistakes: ['Forgetting to consider direction of forces','Confusing mass and weight', 'Thinking action-reaction forces cancel'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'physics_electricity',
    subjectId: 'cambridge_physics',
    title: 'Electricity',
    aliases: ['current', 'voltage', 'resistance', 'circuits', 'electrical circuits'],
    gradeBands: ['Year 6', 'Key Stage 2', 'Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Understand basic circuit components', 'Distinguish series and parallel circuits', 'Understand current and voltage'],
    prerequisites: ['energy basics'],
    commonMistakes: ['Thinking current is used up in a circuit','Confusing series and parallel', 'Misplacing ammeter and voltmeter'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'physics_waves',
    subjectId: 'cambridge_physics',
    title: 'Waves',
    aliases: ['light waves', 'sound waves', 'wave properties', 'electromagnetic spectrum'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Understand wave properties', 'Distinguish transverse and longitudinal waves', 'Explore wave behaviors'],
    prerequisites: ['energy basics'],
    commonMistakes: ['Thinking waves transfer matter','Confusing frequency and amplitude', 'Misunderstanding wave speed'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── ICT ───
  {
    topicId: 'ict_computer_basics',
    subjectId: 'cambridge_ict',
    title: 'Computer Basics',
    aliases: ['computers', 'hardware', 'software', 'computer parts'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4', 'Key Stage 1', 'Key Stage 2'],
    levels: ['beginner'],
    learningObjectives: ['Identify basic computer parts','Understand hardware vs software', 'Use basic computer functions'],
    prerequisites: [],
    commonMistakes: ['Confusing hardware and software','Thinking internet and web are the same', 'Misunderstanding storage vs memory'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'ict_internet_safety',
    subjectId: 'cambridge_ict',
    title: 'Internet Safety',
    aliases: ['online safety', 'e-safety', 'cyber safety', 'digital citizenship'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand risks online', 'Protect personal information', 'Recognize safe online behavior'],
    prerequisites: ['computer basics'],
    commonMistakes: ['Sharing passwords with friends','Thinking private browsing is fully anonymous', 'Trusting all online information'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'ict_spreadsheets',
    subjectId: 'cambridge_ict',
    title: 'Spreadsheets',
    aliases: ['excel', 'sheets', 'data entry', 'formulas'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Enter and format data in spreadsheets','Use basic formulas', 'Create simple charts'],
    prerequisites: ['computer basics', 'basic math'],
    commonMistakes: ['Forgetting equals sign for formulas','Confusing rows and columns', 'Hardcoding values instead of using formulas'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'ict_programming_basics',
    subjectId: 'cambridge_ict',
    title: 'Programming Basics',
    aliases: ['coding basics', 'introduction to programming', 'algorithms', 'scratch', 'python basics'],
    gradeBands: ['Key Stage 2', 'Key Stage 3', 'Key Stage 4'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand what algorithms are', 'Write simple programs', 'Debug basic errors'],
    prerequisites: ['computer basics', 'logical thinking'],
    commonMistakes: ['Forgetting to initialize variables','Infinite loops', 'Off-by-one errors in loops'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Business ───
  {
    topicId: 'business_needs_and_wants',
    subjectId: 'cambridge_business',
    title: 'Needs and Wants',
    aliases: ['needs vs wants', 'basic economic concepts', 'scarcity'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner'],
    learningObjectives: ['Distinguish between needs and wants','Understand scarcity', 'Make basic economic choices'],
    prerequisites: [],
    commonMistakes: ['Thinking all wants are unnecessary','Confusing needs with luxuries', 'Not considering opportunity cost'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'business_production',
    subjectId: 'cambridge_business',
    title: 'Production',
    aliases: ['factors of production', 'goods and services', 'production process'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Identify factors of production','Understand goods vs services', 'Describe production stages'],
    prerequisites: ['needs and wants'],
    commonMistakes: ['Confusing capital goods with finance','Thinking all production is manufacturing', 'Forgetting enterprise as a factor'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'business_entrepreneurship',
    subjectId: 'cambridge_business',
    title: 'Entrepreneurship',
    aliases: ['entrepreneur', 'starting a business', 'business ideas'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Understand what entrepreneurs do','Identify business opportunities', 'Understand risks and rewards'],
    prerequisites: ['needs and wants', 'production'],
    commonMistakes: ['Thinking entrepreneurs only care about profit','Underestimating risk', 'Confusing revenue with profit'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'business_marketing_basics',
    subjectId: 'cambridge_business',
    title: 'Marketing Basics',
    aliases: ['marketing', 'promotion', 'advertising', 'market research'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Understand the purpose of marketing','Identify marketing mix elements', 'Describe promotion methods'],
    prerequisites: ['needs and wants'],
    commonMistakes: ['Thinking marketing is just advertising','Confusing target market with all customers', 'Ignoring market research'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Statistics ───
  {
    topicId: 'stats_data_collection',
    subjectId: 'cambridge_statistics',
    title: 'Data Collection',
    aliases: ['collecting data', 'surveys', 'data sources', 'primary and secondary data'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify data collection methods','Distinguish primary and secondary data', 'Design simple surveys'],
    prerequisites: ['basic math'],
    commonMistakes: ['Biased sampling','Confusing primary and secondary data', 'Leading survey questions'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'stats_averages',
    subjectId: 'cambridge_statistics',
    title: 'Averages',
    aliases: ['mean', 'median', 'mode', 'range', 'measures of central tendency'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Calculate mean, median, mode, range','Choose appropriate average', 'Interpret averages in context'],
    prerequisites: ['data collection', 'basic arithmetic'],
    commonMistakes: ['Confusing mean and median','Not ordering data before finding median', 'Forgetting to include all values'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'stats_charts',
    subjectId: 'cambridge_statistics',
    title: 'Charts and Graphs',
    aliases: ['bar charts', 'line graphs', 'pie charts', 'data representation'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Create bar charts and line graphs','Interpret data from charts', 'Choose appropriate chart type'],
    prerequisites: ['data collection'],
    commonMistakes: ['Misleading axis scales','Using wrong chart type', 'Forgetting to label axes'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'stats_probability_basics',
    subjectId: 'cambridge_statistics',
    title: 'Probability Basics',
    aliases: ['probability', 'chance', 'likelihood', 'likely unlikely certain impossible'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand probability scale','Calculate simple probabilities', 'Use probability language'],
    prerequisites: ['fractions'],
    commonMistakes: ['Thinking probability can be above 1','Confusing theoretical and experimental probability', 'Assuming past events affect independent events'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Literature ───
  {
    topicId: 'literature_poetry',
    subjectId: 'cambridge_literature',
    title: 'Poetry',
    aliases: ['poems', 'verse', 'rhyme', 'poetic devices'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Identify poetic devices','Analyze poem meaning', 'Appreciate different poetic forms'],
    prerequisites: ['basic reading comprehension'],
    commonMistakes: ['Literal interpretation only','Ignoring poetic devices', 'Confusing speaker with poet'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'literature_prose',
    subjectId: 'cambridge_literature',
    title: 'Prose Analysis',
    aliases: ['fiction analysis', 'novel study', 'short stories', 'character analysis'],
    gradeBands: ['Key Stage 2', 'Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Analyze characters and themes','Understand plot structure', 'Identify literary techniques'],
    prerequisites: ['comprehension'],
    commonMistakes: ['Summary instead of analysis','Ignoring authorial intent', 'Not using textual evidence'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'literature_drama',
    subjectId: 'cambridge_literature',
    title: 'Drama',
    aliases: ['plays', 'theatre', 'shakespeare', 'dramatic techniques'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Understand dramatic structure','Analyze character through dialogue', 'Explore theatrical techniques'],
    prerequisites: ['comprehension'],
    commonMistakes: ['Reading play as prose','Ignoring stage directions', 'Confusing monologue and soliloquy'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Geography ───
  {
    topicId: 'geography_map_skills',
    subjectId: 'cambridge_geography',
    title: 'Map Skills',
    aliases: ['maps', 'atlas', 'compass directions', 'grid references'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Use compass directions','Read map symbols', 'Use grid references'],
    prerequisites: [],
    commonMistakes: ['Confusing longitude and latitude','Reading grid references in wrong order', 'Misunderstanding map scale'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'geography_physical_geography',
    subjectId: 'cambridge_geography',
    title: 'Physical Geography',
    aliases: ['rivers', 'mountains', 'volcanoes', 'earthquakes', 'weather and climate'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify physical features','Understand weather vs climate', 'Describe natural processes'],
    prerequisites: [],
    commonMistakes: ['Confusing weather and climate','Thinking volcanoes are random', 'Misunderstanding tectonic plates'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'geography_human_geography',
    subjectId: 'cambridge_geography',
    title: 'Human Geography',
    aliases: ['settlements', 'population', 'urbanization', 'economic activity'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 2', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Understand settlement patterns','Describe population distribution', 'Explore economic activities'],
    prerequisites: ['map skills'],
    commonMistakes: ['Confusing urban and rural','Thinking all countries develop the same way', 'Ignoring environmental impact'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── History ───
  {
    topicId: 'history_ancient_civilizations',
    subjectId: 'cambridge_history',
    title: 'Ancient Civilizations',
    aliases: ['ancient egypt', 'ancient greece', 'ancient rome', 'mesopotamia', 'indus valley'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6', 'Key Stage 2'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify key ancient civilizations','Understand their contributions', 'Compare civilizations'],
    prerequisites: [],
    commonMistakes: ['Confusing timelines of civilizations','Thinking all ancient cultures are the same', 'Overgeneralizing from limited evidence'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'history_modern_history',
    subjectId: 'cambridge_history',
    title: 'Modern History',
    aliases: ['world wars', 'industrial revolution', '20th century', 'modern period'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Understand key modern events','Analyze causes and consequences', 'Evaluate historical sources'],
    prerequisites: ['basic history vocabulary'],
    commonMistakes: ['Presentism judging past events','Confusing correlation with causation', 'Relying on single perspectives'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'history_source_analysis',
    subjectId: 'cambridge_history',
    title: 'Source Analysis',
    aliases: ['historical sources', 'primary sources', 'secondary sources', 'evidence evaluation'],
    gradeBands: ['Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate', 'advanced'],
    learningObjectives: ['Distinguish primary and secondary sources','Evaluate source reliability', 'Use sources as evidence'],
    prerequisites: ['basic history vocabulary'],
    commonMistakes: ['Taking sources at face value','Ignoring source bias', 'Not considering historical context'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },

  // ─── Global Perspectives ───
  {
    topicId: 'gp_sustainability',
    subjectId: 'cambridge_global_perspectives',
    title: 'Sustainability',
    aliases: ['sustainable development', 'environment', 'climate action', 'green living'],
    gradeBands: ['Key Stage 2', 'Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Understand sustainability concept','Identify sustainable practices', 'Explore global environmental challenges'],
    prerequisites: [],
    commonMistakes: ['Thinking sustainability is only environmental','Confusing sustainability with recycling only', 'Ignoring social and economic dimensions'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
  {
    topicId: 'gp_global_issues',
    subjectId: 'cambridge_global_perspectives',
    title: 'Global Issues',
    aliases: ['world problems', 'poverty', 'equality', 'health', 'education'],
    gradeBands: ['Key Stage 2', 'Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Identify major global issues','Understand multiple perspectives', 'Explore possible solutions'],
    prerequisites: [],
    commonMistakes: ['Oversimplifying complex issues','Assuming single cause for global problems', 'Ignoring cultural context'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'none',
  },
];
