import type { TopicSeed } from '../subjectTopicMapContracts';

export const madrasaDeenTopicSeeds: TopicSeed[] = [
  // ─── Arabic ───
  {
    topicId: 'arabic_letters',
    subjectId: 'deen_arabic',
    title: 'Arabic Letters',
    aliases: ['arabic alphabet', 'huruf', 'arabic script', 'writing arabic letters'],
    gradeBands: ['Foundation', 'Year 1', 'Year 2'],
    levels: ['beginner'],
    learningObjectives: ['Recognise Arabic letters in isolate and joined forms', 'Pronounce each letter correctly', 'Write letters from right to left'],
    prerequisites: [],
    commonMistakes: ['Confusing similar sounding letters','Writing from left to right', 'Mixing up letter shapes in different positions'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'arabic_sounds',
    subjectId: 'deen_arabic',
    title: 'Arabic Sounds and Pronunciation',
    aliases: ['makharij', 'arabic phonics', 'pronunciation', 'arabic sounds'],
    gradeBands: ['Foundation', 'Year 1', 'Year 2'],
    levels: ['beginner'],
    learningObjectives: ['Identify articulation points of letters', 'Pronounce emphatic letters correctly', 'Distinguish similar sound pairs'],
    prerequisites: ['arabic letters'],
    commonMistakes: ['Pronouncing ع and أ the same','Not differentiating emphatic letters', 'Dropping throat letters'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'arabic_basic_vocabulary',
    subjectId: 'deen_arabic',
    title: 'Basic Arabic Vocabulary',
    aliases: ['arabic words', 'common arabic words', 'essential vocabulary'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3'],
    levels: ['beginner'],
    learningObjectives: ['Learn common everyday Arabic words','Understand basic nouns and verbs', 'Build simple sentences'],
    prerequisites: ['arabic letters'],
    commonMistakes: ['Confusing words with similar roots','Using feminine forms incorrectly', 'Mispronouncing words from writing alone'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'arabic_simple_reading',
    subjectId: 'deen_arabic',
    title: 'Simple Arabic Reading',
    aliases: ['arabic reading practice', 'reading arabic', 'basic arabic texts'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Read simple Arabic sentences','Understand short passages', 'Build reading fluency'],
    prerequisites: ['arabic letters', 'arabic basic vocabulary'],
    commonMistakes: ['Reading without understanding','Ignoring tashkeel', 'Skipping unfamiliar words'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },

  // ─── Qur'an ───
  {
    topicId: 'quran_recitation_basics',
    subjectId: 'deen_quran',
    title: 'Qur\'an Recitation Basics',
    aliases: ['quran reading', 'tilawah basics', 'qira\'ah', 'how to recite quran'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Recite short surahs correctly','Apply basic tajweed rules', 'Understand etiquette of recitation'],
    prerequisites: ['arabic letters', 'arabic sounds'],
    commonMistakes: ['Rushing through recitation','Neglecting tajweed rules', 'Incorrect stopping and starting'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'quran_memorization',
    subjectId: 'deen_quran',
    title: 'Qur\'an Memorization Support',
    aliases: ['hifdh', 'memorising quran', 'surah memorisation', 'juz amma'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Memorise short surahs','Use repetition techniques', 'Maintain previously memorised portions'],
    prerequisites: ['quran recitation basics'],
    commonMistakes: ['Moving to next ayah before mastering current','Neglecting revision of earlier surahs', 'Poor pronunciation during memorisation'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'quran_surah_review',
    subjectId: 'deen_quran',
    title: 'Surah Review',
    aliases: ['surah revision', 'quran revision', 'reviewing surahs'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Review and retain memorised surahs','Improve fluency in recitation', 'Strengthen long-term retention'],
    prerequisites: ['quran memorization'],
    commonMistakes: ['Skipping difficult passages','Not reviewing regularly', 'Losing previously memorised portions'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },

  // ─── Hadith ───
  {
    topicId: 'hadith_meaning',
    subjectId: 'deen_hadith',
    title: 'Meaning of Hadith',
    aliases: ['what is hadith', 'understanding hadith', 'introduction to hadith'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner'],
    learningObjectives: ['Understand what hadith means', 'Distinguish hadith from Qur\'an', 'Appreciate the importance of hadith'],
    prerequisites: ['basic islamic knowledge'],
    commonMistakes: ['Confusing hadith with quran','Thinking all hadith are equally authentic', 'Taking hadith out of context'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'hadith_manners',
    subjectId: 'deen_hadith',
    title: 'Manners from Hadith',
    aliases: ['hadith on manners', 'prophetic manners', 'adab in hadith'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner'],
    learningObjectives: ['Learn hadith about good manners', 'Apply prophetic teachings in daily life', 'Memorise short hadith on character'],
    prerequisites: ['basic islamic knowledge'],
    commonMistakes: ['Memorising without understanding application','Forgetting context of the hadith', 'Selective application of teachings'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'hadith_authenticity_basics',
    subjectId: 'deen_hadith',
    title: 'Hadith Authenticity Basics',
    aliases: ['authentic hadith', 'sahih', 'hasan', 'da\'if', 'hadith classification'],
    gradeBands: ['Key Stage 4', 'Advanced'],
    levels: ['advanced'],
    learningObjectives: ['Understand basic hadith classification','Recognise major hadith collections', 'Appreciate the science of hadith'],
    prerequisites: ['hadith meaning'],
    commonMistakes: ['Assuming all hadith in popular books are authentic','Ignoring chain of narration', 'Over-applying weak hadith'],
    sourceConfidence: 'future_source_required',
    deenSensitivityLevel: 'source_required',
  },

  // ─── Seerah ───
  {
    topicId: 'seerah_early_life',
    subjectId: 'deen_seerah',
    title: 'Early Life of the Prophet',
    aliases: ['prophet childhood', 'birth of prophet', 'early seerah', 'pre-prophethood'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4', 'Year 5'],
    levels: ['beginner'],
    learningObjectives: ['Learn about the Prophet\'s birth and early life', 'Understand the environment of Makkah', 'Appreciate his character before prophethood'],
    prerequisites: [],
    commonMistakes: ['Conflicting with later events','Over-idealising without historical context', 'Mixing weak narrations with authentic'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'seerah_major_lessons',
    subjectId: 'deen_seerah',
    title: 'Major Lessons from Seerah',
    aliases: ['seerah lessons', 'prophetic example', 'lessons from prophets life'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Identify key lessons from the Prophet\'s life', 'Understand his character as a model', 'Apply seerah lessons to daily life'],
    prerequisites: ['seerah early life'],
    commonMistakes: ['Reducing seerah to stories without reflection','Focusing only on miraculous aspects', 'Taking events out of historical context'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'seerah_makkan_period',
    subjectId: 'deen_seerah',
    title: 'Makkan Period',
    aliases: ['meccan period', 'early islam in makkah', 'persecution in makkah'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Understand the challenges of early Muslims in Makkah','Learn about key events in Makkah', 'Draw lessons from perseverance'],
    prerequisites: ['seerah early life'],
    commonMistakes: ['Simplifying the complexity of the period','Focusing only on persecution', 'Missing the strategic wisdom of the Prophet'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'seerah_madani_period',
    subjectId: 'deen_seerah',
    title: 'Madani Period',
    aliases: ['medinan period', 'state of medina', 'constitution of medina'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 3', 'Key Stage 4'],
    levels: ['intermediate'],
    learningObjectives: ['Understand the establishment of the first Muslim community','Learn about key battles and treaties', 'Draw lessons in leadership'],
    prerequisites: ['seerah makkan period'],
    commonMistakes: ['Over-simplifying military campaigns','Treating treaties as failures', 'Ignoring the social reforms of the period'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },

  // ─── Fiqh ───
  {
    topicId: 'fiqh_wudu_basics',
    subjectId: 'deen_fiqh',
    title: 'Wudu Basics',
    aliases: ['ablution', 'wudhu', 'how to make wudu', 'steps of wudu'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3'],
    levels: ['beginner'],
    learningObjectives: ['Learn the steps of wudu','Understand what breaks wudu', 'Know the importance of cleanliness'],
    prerequisites: [],
    commonMistakes: ['Wasting water','Missing parts of the face or hands', 'Not washing each part properly'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'fiqh_salah_basics',
    subjectId: 'deen_fiqh',
    title: 'Salah Basics',
    aliases: ['prayer basics', 'how to pray', 'daily prayers', 'salat'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Learn the steps of salah','Know the number of daily prayers', 'Understand the importance of prayer'],
    prerequisites: ['wudu basics'],
    commonMistakes: ['Rushing through prayer without focus','Incorrect recitation', 'Forgetting essential parts of prayer'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'fiqh_fasting_basics',
    subjectId: 'deen_fiqh',
    title: 'Fasting Basics',
    aliases: ['sawm', 'ramadan fasting', 'how to fast', 'fasting in islam'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner'],
    learningObjectives: ['Understand the ruling of fasting','Learn what breaks the fast', 'Know the blessings of Ramadan'],
    prerequisites: [],
    commonMistakes: ['Eating or drinking forgetfully and thinking fast is broken','Skipping suhoor', 'Focusing only on food and drink, not behaviour'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'fiqh_zakat_basics',
    subjectId: 'deen_fiqh',
    title: 'Zakat Basics',
    aliases: ['zakat', 'charity in islam', 'obligatory charity', 'zakah'],
    gradeBands: ['Year 5', 'Year 6', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Understand the meaning of zakat','Learn who must pay zakat', 'Know who receives zakat'],
    prerequisites: ['basic islamic knowledge'],
    commonMistakes: ['Confusing zakat with sadaqah','Not knowing nisab threshold', 'Delaying payment without reason'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'fiqh_advanced_rulings',
    subjectId: 'deen_fiqh',
    title: 'Advanced Fiqh Rulings',
    aliases: ['fiqh details', 'advanced rulings', 'detailed jurisprudence'],
    gradeBands: ['Key Stage 4', 'Advanced'],
    levels: ['advanced'],
    learningObjectives: ['Understand detailed fiqh rulings','Explore different scholarly opinions', 'Appreciate the methodology of fiqh'],
    prerequisites: ['fiqh salah basics'],
    commonMistakes: ['Following opinions without understanding evidence','Treating one school as the only valid one', 'Applying rulings without proper context'],
    sourceConfidence: 'future_source_required',
    deenSensitivityLevel: 'scholar_referral_later',
  },

  // ─── Tawheed ───
  {
    topicId: 'tawheed_belief_in_allah',
    subjectId: 'deen_tawheed',
    title: 'Belief in Allah',
    aliases: ['iman in allah', 'believing in allah', 'who is allah'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3'],
    levels: ['beginner'],
    learningObjectives: ['Understand that Allah is one', 'Learn some of Allah\'s attributes with caution', 'Develop love for Allah'],
    prerequisites: [],
    commonMistakes: ['Attempting to visualize Allah','Comparing Allah to creation', 'Over-specifying attributes without knowledge'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'tawheed_names_and_attributes',
    subjectId: 'deen_tawheed',
    title: 'Names and Attributes of Allah',
    aliases: ['asmaa allah', '99 names', 'allahs names', 'sifaat allah'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4', 'Year 5'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Learn some names of Allah', 'Understand the meanings of key names', 'Apply knowledge of Allah\'s names in daily life'],
    prerequisites: ['belief in allah'],
    commonMistakes: ['Making anthropomorphic comparisons','Speculating on the nature of attributes', 'Using names without proper understanding'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'tawheed_advanced_theology',
    subjectId: 'deen_tawheed',
    title: 'Advanced Tawheed Topics',
    aliases: ['aqeedah details', 'advanced creed', 'theological discussions'],
    gradeBands: ['Key Stage 4', 'Advanced'],
    levels: ['advanced'],
    learningObjectives: ['Understand deeper theological concepts','Explore scholarly views on creed', 'Appreciate the breadth of Islamic theology'],
    prerequisites: ['tawheed names and attributes'],
    commonMistakes: ['Engaging in speculative theology without foundation','Picking one opinion without evidence', 'Dividing over theological differences'],
    sourceConfidence: 'future_source_required',
    deenSensitivityLevel: 'scholar_referral_later',
  },

  // ─── Tafsir ───
  {
    topicId: 'tafsir_simple_meaning',
    subjectId: 'deen_tafsir',
    title: 'Simple Meaning Support',
    aliases: ['quran meaning', 'understanding quran', 'simple tafsir', 'tafsir simple meaning'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand the basic meaning of verses', 'Learn the context of revelation (asbab al-nuzul)', 'Appreciate the message of the Qur\'an'],
    prerequisites: ['quran recitation basics'],
    commonMistakes: ['Literal interpretation without context','Ignoring the context of revelation', 'Applying verses without scholarly guidance'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'source_required',
  },
  {
    topicId: 'tafsir_detailed_commentary',
    subjectId: 'deen_tafsir',
    title: 'Detailed Tafsir Commentary',
    aliases: ['in-depth tafsir', 'detailed quran explanation', 'comprehensive tafsir'],
    gradeBands: ['Key Stage 4', 'Advanced'],
    levels: ['advanced'],
    learningObjectives: ['Understand different tafsir approaches','Engage with scholarly tafsir works', 'Appreciate linguistic and historical dimensions'],
    prerequisites: ['tafsir simple meaning', 'arabic grammar basics'],
    commonMistakes: ['Choosing one tafsir as the only valid one','Ignoring scholarly consensus', 'Personal interpretation without proper knowledge'],
    sourceConfidence: 'future_source_required',
    deenSensitivityLevel: 'source_required',
  },

  // ─── Tadabbur ───
  {
    topicId: 'tadabbur_reflection_intro',
    subjectId: 'deen_tadabbur',
    title: 'Introduction to Tadabbur',
    aliases: ['quran reflection', 'pondering quran', 'contemplation'],
    gradeBands: ['Year 4', 'Year 5', 'Year 6', 'Key Stage 3'],
    levels: ['intermediate'],
    learningObjectives: ['Understand the meaning of tadabbur', 'Learn how to reflect on verses', 'Connect Qur\'an to daily life'],
    prerequisites: ['tafsir simple meaning'],
    commonMistakes: ['Over-interpreting without knowledge','Projecting personal opinions onto the text', 'Neglecting scholarly interpretations'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'tadabbur_guidance_and_caution',
    subjectId: 'deen_tadabbur',
    title: 'Advanced Tadabbur with Caution',
    aliases: ['deep quran reflection', 'contemplation guidance'],
    gradeBands: ['Key Stage 4', 'Advanced'],
    levels: ['advanced'],
    learningObjectives: ['Develop structured reflection practice','Understand boundaries in interpretation', 'Seek scholarly guidance for deeper meanings'],
    prerequisites: ['tadabbur reflection intro'],
    commonMistakes: ['Claiming certainty in personal reflections','Going beyond established tafsir', 'Teaching personal reflections as definitive'],
    sourceConfidence: 'future_source_required',
    deenSensitivityLevel: 'source_required',
  },

  // ─── Adab ───
  {
    topicId: 'adab_respect',
    subjectId: 'deen_adab',
    title: 'Respect in Islam',
    aliases: ['respect', 'honouring parents', 'respecting teachers', 'respecting elders'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Understand the importance of respect in Islam','Learn how to show respect to parents and teachers', 'Practice good manners with others'],
    prerequisites: [],
    commonMistakes: ['Being respectful only when being watched','Confusing respect with fear', 'Neglecting respect for younger children'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'adab_honesty',
    subjectId: 'deen_adab',
    title: 'Honesty',
    aliases: ['truthfulness', 'sidq', 'being honest', 'telling the truth'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Understand why honesty is important in Islam','Practice truthfulness in speech and actions', 'Recognise the harms of dishonesty'],
    prerequisites: [],
    commonMistakes: ['Lying to avoid trouble','Thinking small lies are acceptable', 'Confusing honesty with being unkind'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'adab_kindness',
    subjectId: 'deen_adab',
    title: 'Kindness',
    aliases: ['kindness in islam', 'compassion', 'mercy', 'rahmah'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Learn the value of kindness in Islam','Practice kindness to family, neighbours, and animals', 'Understand that kindness is part of faith'],
    prerequisites: [],
    commonMistakes: ['Being kind only to those who are kind back','Neglecting kindness at home', 'Thinking kindness is weakness'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'adab_manners_eating',
    subjectId: 'deen_adab',
    title: 'Islamic Manners of Eating',
    aliases: ['eating etiquette', 'table manners islam', 'bismillah before eating'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3'],
    levels: ['beginner'],
    learningObjectives: ['Learn Islamic etiquettes of eating','Say Bismillah before eating', 'Eat with the right hand'],
    prerequisites: [],
    commonMistakes: ['Forgetting to say Bismillah','Eating too quickly', 'Wasting food'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },

  // ─── Du'a ───
  {
    topicId: 'dua_daily_duas',
    subjectId: 'deen_dua',
    title: 'Daily Du\'as',
    aliases: ['everyday duas', 'duas for daily life', 'morning duas', 'evening duas', 'daily duas'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Learn daily du\'as for common situations', 'Understand the meaning of each du\'a', 'Make du\'a a daily habit'],
    prerequisites: [],
    commonMistakes: ['Reciting without understanding', 'Rushing through du\'a', 'Forgetting to make du\'a regularly'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'dua_meaning_and_etiquette',
    subjectId: 'deen_dua',
    title: 'Meaning and Etiquette of Du\'a',
    aliases: ['how to make dua', 'dua etiquette', 'conditions of dua', 'adab of dua'],
    gradeBands: ['Year 3', 'Year 4', 'Year 5', 'Year 6'],
    levels: ['beginner', 'intermediate'],
    learningObjectives: ['Understand what du\'a is and its importance', 'Learn proper etiquette of making du\'a', 'Know times when du\'a is more likely accepted'],
    prerequisites: ['daily duas'],
    commonMistakes: ['Thinking du\'a is only for requests', 'Being impatient when du\'a is not answered immediately', 'Not having sincerity in du\'a'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },

  // ─── Islamic Manners and Character ───
  {
    topicId: 'islamic_manners_introduction',
    subjectId: 'deen_islamic_manners',
    title: 'Introduction to Islamic Manners',
    aliases: ['good character in islam', 'akhlaq introduction', 'islamic etiquette basics'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3'],
    levels: ['beginner'],
    learningObjectives: ['Understand what Islamic manners are', 'Learn why character matters in Islam', 'Begin practising good manners'],
    prerequisites: [],
    commonMistakes: ['Thinking manners are optional in Islam', 'Separating character from faith', 'Being polite outside but rude at home'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'islamic_manners_greetings',
    subjectId: 'deen_islamic_manners',
    title: 'Islamic Greetings',
    aliases: ['assalamu alaikum', 'salaam', 'greeting in islam', 'islamic greeting'],
    gradeBands: ['Year 1', 'Year 2', 'Year 3'],
    levels: ['beginner'],
    learningObjectives: ['Learn the Islamic greeting', 'Respond properly to greetings', 'Spread salaam to others'],
    prerequisites: [],
    commonMistakes: ['Only greeting people you know', 'Mumbling the greeting', 'Not returning a better greeting'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
  {
    topicId: 'islamic_manners_neighbours',
    subjectId: 'deen_islamic_manners',
    title: 'Rights of Neighbours',
    aliases: ['neighbours in islam', 'good neighbour', 'neighbour rights'],
    gradeBands: ['Year 2', 'Year 3', 'Year 4'],
    levels: ['beginner'],
    learningObjectives: ['Understand the rights of neighbours in Islam', 'Practice good treatment of neighbours', 'Recognise the importance of community'],
    prerequisites: ['introduction to islamic manners'],
    commonMistakes: ['Only being good to Muslim neighbours', 'Ignoring neighbours in need', 'Causing harm or annoyance to neighbours'],
    sourceConfidence: 'draft_seed',
    deenSensitivityLevel: 'basic',
  },
];

