import { describe, it, expect } from 'vitest';
import { validateTask034ReportTruth } from '../lib/task034ControlledLimitedRolloutValidation';

describe('task034 report truth smoke', () => {
  it('valid report with all fields set correctly passes', () => {
    const result = validateTask034ReportTruth({
      taskId: 'task-034',
      scope: 'controlled-limited-rollout',
      task033DependencyCommit: '276445d',
      task033DependencyVerified: true,
      task034Started: false,
      task035Started: false,
      task040Started: false,
      frontendUiCreated: false,
      schoolWideLaunchCreated: false,
      backendFreezeCreated: false,
      hundredPercentRolloutCreated: false,
      productionDeploymentIntroduced: false,
      realNotificationsSent: false,
      liveAiCallIntroduced: false,
      liveSchoolConnectorWriteIntroduced: false,
      productionDataMutationExecuted: false,
      rawPrivateDataStored: false,
      controlledLimitedRolloutCreated: true,
      contractsCreatedOrUpdated: true,
      validationCreatedOrUpdated: true,
      repositoryCreatedOrUpdated: true,
      servicesCreatedOrUpdated: true,
      routesCreatedOrUpdated: true,
      routesMountedOrDirectlyTested: true,
      verifiedSchoolContextRequired: true,
      task033AcceptanceRequired: true,
      rolloutEnvironmentGatePassed: true,
      limitedRolloutConfigPassed: true,
      rolloutCapGatePassed: true,
      expandedCohortEligibilityPassed: true,
      staffReadinessPassed: true,
      learnerNoticeReadinessPassed: true,
      controlledRolloutStateMachinePassed: true,
      controlledRolloutEventIntakePassed: true,
      expandedRuntimeGuardPassed: true,
      healthBudgetEscalationPassed: true,
      incidentEscalationBridgePassed: true,
      rollbackProtectionPassed: true,
      privacyReviewPassed: true,
      contentGovernanceReviewPassed: true,
      socraticIntegrityReviewPassed: true,
      deenBoundaryReviewPassed: true,
      schoolIdentityReviewPassed: true,
      crossSchoolDenialReviewPassed: true,
      safeRolloutReadModelPassed: true,
      evidenceLedgerPassed: true,
      diagnosticsPassed: true,
      postLimitedRolloutDecisionPassed: true,
      reportPassed: true,
      task034FocusedTestsRun: true,
      task034FocusedTestsPassed: true,
      task034FocusedTestFiles: 25,
      task034FocusedTestsPassedCount: 25,
      task034FocusedTestsFailedCount: 0,
      task020To033RegressionRun: true,
      task020To033RegressionPassed: true,
      phase3RegressionRun: true,
      phase3RegressionPassed: true,
      fullBackendSuiteRun: true,
      fullBackendSuitePassed: true,
      fullBackendSuiteFailedFiles: [],
      fullBackendSuiteFailedTests: [],
      prismaValidateRun: true,
      prismaValidatePassed: true,
      prismaGenerateRun: true,
      prismaGeneratePassed: true,
      backendBuildRun: true,
      backendBuildPassed: true,
      backendTypecheckRun: true,
      backendTypecheckPassed: true,
      task034VerificationScriptRun: true,
      task034VerificationScriptPassed: true,
      privacyScanRun: true,
      privacyScanPassed: true,
      noProductionMutationScanRun: true,
      noProductionMutationScanPassed: true,
      noLiveConnectorAiScanRun: true,
      noLiveConnectorAiScanPassed: true,
      noLiveNotificationScanRun: true,
      noLiveNotificationScanPassed: true,
      noFrontendUiScanRun: true,
      noFrontendUiScanPassed: true,
      noTask035ToTask040ScanRun: true,
      noTask035ToTask040ScanPassed: true,
      noFalsePassScanRun: true,
      noFalsePassScanPassed: true,
      safeToStartTask035: false,
      safeToStartTask040: false,
      verdict: 'TASK_034_PASS_SAFE_TO_START_TASK_035',
      commandsRun: [],
      filesCreated: [],
      filesModified: [],
      filesStaged: [],
      filesIntentionallyNotStaged: [],
      remainingBlockers: [],
      generatedAt: '2026-07-10T00:00:00.000Z',
    });
    expect(result.ok).toBe(true);
    expect(result.reasonCodes).toEqual([]);
  });

  it('null input fails', () => {
    const result = validateTask034ReportTruth(null as any);
    expect(result.ok).toBe(false);
    expect(result.reasonCodes).toContain('input_is_null');
  });

  it('task034Started true fails', () => {
    const base = {
      taskId: 'task-034', scope: 'controlled-limited-rollout',
      task033DependencyCommit: '276445d', task033DependencyVerified: true,
      task034Started: true, task035Started: false, task040Started: false,
      frontendUiCreated: false, schoolWideLaunchCreated: false,
      backendFreezeCreated: false, hundredPercentRolloutCreated: false,
      productionDeploymentIntroduced: false, realNotificationsSent: false,
      liveAiCallIntroduced: false, liveSchoolConnectorWriteIntroduced: false,
      productionDataMutationExecuted: false, rawPrivateDataStored: false,
      controlledLimitedRolloutCreated: true,
      contractsCreatedOrUpdated: true, validationCreatedOrUpdated: true,
      repositoryCreatedOrUpdated: true, servicesCreatedOrUpdated: true,
      routesCreatedOrUpdated: true, routesMountedOrDirectlyTested: true,
      verifiedSchoolContextRequired: true, task033AcceptanceRequired: true,
      rolloutEnvironmentGatePassed: true, limitedRolloutConfigPassed: true,
      rolloutCapGatePassed: true, expandedCohortEligibilityPassed: true,
      staffReadinessPassed: true, learnerNoticeReadinessPassed: true,
      controlledRolloutStateMachinePassed: true, controlledRolloutEventIntakePassed: true,
      expandedRuntimeGuardPassed: true, healthBudgetEscalationPassed: true,
      incidentEscalationBridgePassed: true, rollbackProtectionPassed: true,
      privacyReviewPassed: true, contentGovernanceReviewPassed: true,
      socraticIntegrityReviewPassed: true, deenBoundaryReviewPassed: true,
      schoolIdentityReviewPassed: true, crossSchoolDenialReviewPassed: true,
      safeRolloutReadModelPassed: true, evidenceLedgerPassed: true,
      diagnosticsPassed: true, postLimitedRolloutDecisionPassed: true,
      reportPassed: true,
      task034FocusedTestsRun: true, task034FocusedTestsPassed: true,
      task034FocusedTestFiles: 25, task034FocusedTestsPassedCount: 25,
      task034FocusedTestsFailedCount: 0,
      task020To033RegressionRun: true, task020To033RegressionPassed: true,
      phase3RegressionRun: true, phase3RegressionPassed: true,
      fullBackendSuiteRun: true, fullBackendSuitePassed: true,
      fullBackendSuiteFailedFiles: [], fullBackendSuiteFailedTests: [],
      prismaValidateRun: true, prismaValidatePassed: true,
      prismaGenerateRun: true, prismaGeneratePassed: true,
      backendBuildRun: true, backendBuildPassed: true,
      backendTypecheckRun: true, backendTypecheckPassed: true,
      task034VerificationScriptRun: true, task034VerificationScriptPassed: true,
      privacyScanRun: true, privacyScanPassed: true,
      noProductionMutationScanRun: true, noProductionMutationScanPassed: true,
      noLiveConnectorAiScanRun: true, noLiveConnectorAiScanPassed: true,
      noLiveNotificationScanRun: true, noLiveNotificationScanPassed: true,
      noFrontendUiScanRun: true, noFrontendUiScanPassed: true,
      noTask035ToTask040ScanRun: true, noTask035ToTask040ScanPassed: true,
      noFalsePassScanRun: true, noFalsePassScanPassed: true,
      safeToStartTask035: false, safeToStartTask040: false,
      verdict: 'TASK_034_PASS_SAFE_TO_START_TASK_035',
      commandsRun: [], filesCreated: [], filesModified: [],
      filesStaged: [], filesIntentionallyNotStaged: [],
      remainingBlockers: [], generatedAt: 'ts',
    };
    const result = validateTask034ReportTruth(base);
    expect(result.ok).toBe(false);
    expect(result.reasonCodes).toContain('task034Started_not_false');
  });

  it('frontendUiCreated true fails', () => {
    const base = {
      taskId: 'task-034', scope: 'controlled-limited-rollout',
      task033DependencyCommit: '276445d', task033DependencyVerified: true,
      task034Started: false, task035Started: false, task040Started: false,
      frontendUiCreated: true, schoolWideLaunchCreated: false,
      backendFreezeCreated: false, hundredPercentRolloutCreated: false,
      productionDeploymentIntroduced: false, realNotificationsSent: false,
      liveAiCallIntroduced: false, liveSchoolConnectorWriteIntroduced: false,
      productionDataMutationExecuted: false, rawPrivateDataStored: false,
      controlledLimitedRolloutCreated: true,
      contractsCreatedOrUpdated: true, validationCreatedOrUpdated: true,
      repositoryCreatedOrUpdated: true, servicesCreatedOrUpdated: true,
      routesCreatedOrUpdated: true, routesMountedOrDirectlyTested: true,
      verifiedSchoolContextRequired: true, task033AcceptanceRequired: true,
      rolloutEnvironmentGatePassed: true, limitedRolloutConfigPassed: true,
      rolloutCapGatePassed: true, expandedCohortEligibilityPassed: true,
      staffReadinessPassed: true, learnerNoticeReadinessPassed: true,
      controlledRolloutStateMachinePassed: true, controlledRolloutEventIntakePassed: true,
      expandedRuntimeGuardPassed: true, healthBudgetEscalationPassed: true,
      incidentEscalationBridgePassed: true, rollbackProtectionPassed: true,
      privacyReviewPassed: true, contentGovernanceReviewPassed: true,
      socraticIntegrityReviewPassed: true, deenBoundaryReviewPassed: true,
      schoolIdentityReviewPassed: true, crossSchoolDenialReviewPassed: true,
      safeRolloutReadModelPassed: true, evidenceLedgerPassed: true,
      diagnosticsPassed: true, postLimitedRolloutDecisionPassed: true,
      reportPassed: true,
      task034FocusedTestsRun: true, task034FocusedTestsPassed: true,
      task034FocusedTestFiles: 25, task034FocusedTestsPassedCount: 25,
      task034FocusedTestsFailedCount: 0,
      task020To033RegressionRun: true, task020To033RegressionPassed: true,
      phase3RegressionRun: true, phase3RegressionPassed: true,
      fullBackendSuiteRun: true, fullBackendSuitePassed: true,
      fullBackendSuiteFailedFiles: [], fullBackendSuiteFailedTests: [],
      prismaValidateRun: true, prismaValidatePassed: true,
      prismaGenerateRun: true, prismaGeneratePassed: true,
      backendBuildRun: true, backendBuildPassed: true,
      backendTypecheckRun: true, backendTypecheckPassed: true,
      task034VerificationScriptRun: true, task034VerificationScriptPassed: true,
      privacyScanRun: true, privacyScanPassed: true,
      noProductionMutationScanRun: true, noProductionMutationScanPassed: true,
      noLiveConnectorAiScanRun: true, noLiveConnectorAiScanPassed: true,
      noLiveNotificationScanRun: true, noLiveNotificationScanPassed: true,
      noFrontendUiScanRun: true, noFrontendUiScanPassed: true,
      noTask035ToTask040ScanRun: true, noTask035ToTask040ScanPassed: true,
      noFalsePassScanRun: true, noFalsePassScanPassed: true,
      safeToStartTask035: false, safeToStartTask040: false,
      verdict: 'TASK_034_PASS_SAFE_TO_START_TASK_035',
      commandsRun: [], filesCreated: [], filesModified: [],
      filesStaged: [], filesIntentionallyNotStaged: [],
      remainingBlockers: [], generatedAt: 'ts',
    };
    const result = validateTask034ReportTruth(base);
    expect(result.ok).toBe(false);
    expect(result.reasonCodes).toContain('frontendUiCreated_not_false');
  });

  it('productionDeploymentIntroduced true fails', () => {
    const base = {
      taskId: 'task-034', scope: 'controlled-limited-rollout',
      task033DependencyCommit: '276445d', task033DependencyVerified: true,
      task034Started: false, task035Started: false, task040Started: false,
      frontendUiCreated: false, schoolWideLaunchCreated: false,
      backendFreezeCreated: false, hundredPercentRolloutCreated: false,
      productionDeploymentIntroduced: true, realNotificationsSent: false,
      liveAiCallIntroduced: false, liveSchoolConnectorWriteIntroduced: false,
      productionDataMutationExecuted: false, rawPrivateDataStored: false,
      controlledLimitedRolloutCreated: true,
      contractsCreatedOrUpdated: true, validationCreatedOrUpdated: true,
      repositoryCreatedOrUpdated: true, servicesCreatedOrUpdated: true,
      routesCreatedOrUpdated: true, routesMountedOrDirectlyTested: true,
      verifiedSchoolContextRequired: true, task033AcceptanceRequired: true,
      rolloutEnvironmentGatePassed: true, limitedRolloutConfigPassed: true,
      rolloutCapGatePassed: true, expandedCohortEligibilityPassed: true,
      staffReadinessPassed: true, learnerNoticeReadinessPassed: true,
      controlledRolloutStateMachinePassed: true, controlledRolloutEventIntakePassed: true,
      expandedRuntimeGuardPassed: true, healthBudgetEscalationPassed: true,
      incidentEscalationBridgePassed: true, rollbackProtectionPassed: true,
      privacyReviewPassed: true, contentGovernanceReviewPassed: true,
      socraticIntegrityReviewPassed: true, deenBoundaryReviewPassed: true,
      schoolIdentityReviewPassed: true, crossSchoolDenialReviewPassed: true,
      safeRolloutReadModelPassed: true, evidenceLedgerPassed: true,
      diagnosticsPassed: true, postLimitedRolloutDecisionPassed: true,
      reportPassed: true,
      task034FocusedTestsRun: true, task034FocusedTestsPassed: true,
      task034FocusedTestFiles: 25, task034FocusedTestsPassedCount: 25,
      task034FocusedTestsFailedCount: 0,
      task020To033RegressionRun: true, task020To033RegressionPassed: true,
      phase3RegressionRun: true, phase3RegressionPassed: true,
      fullBackendSuiteRun: true, fullBackendSuitePassed: true,
      fullBackendSuiteFailedFiles: [], fullBackendSuiteFailedTests: [],
      prismaValidateRun: true, prismaValidatePassed: true,
      prismaGenerateRun: true, prismaGeneratePassed: true,
      backendBuildRun: true, backendBuildPassed: true,
      backendTypecheckRun: true, backendTypecheckPassed: true,
      task034VerificationScriptRun: true, task034VerificationScriptPassed: true,
      privacyScanRun: true, privacyScanPassed: true,
      noProductionMutationScanRun: true, noProductionMutationScanPassed: true,
      noLiveConnectorAiScanRun: true, noLiveConnectorAiScanPassed: true,
      noLiveNotificationScanRun: true, noLiveNotificationScanPassed: true,
      noFrontendUiScanRun: true, noFrontendUiScanPassed: true,
      noTask035ToTask040ScanRun: true, noTask035ToTask040ScanPassed: true,
      noFalsePassScanRun: true, noFalsePassScanPassed: true,
      safeToStartTask035: false, safeToStartTask040: false,
      verdict: 'TASK_034_PASS_SAFE_TO_START_TASK_035',
      commandsRun: [], filesCreated: [], filesModified: [],
      filesStaged: [], filesIntentionallyNotStaged: [],
      remainingBlockers: [], generatedAt: 'ts',
    };
    const result = validateTask034ReportTruth(base);
    expect(result.ok).toBe(false);
    expect(result.reasonCodes).toContain('productionDeploymentIntroduced_not_false');
  });

  it('realNotificationsSent true fails', () => {
    const base = {
      taskId: 'task-034', scope: 'controlled-limited-rollout',
      task033DependencyCommit: '276445d', task033DependencyVerified: true,
      task034Started: false, task035Started: false, task040Started: false,
      frontendUiCreated: false, schoolWideLaunchCreated: false,
      backendFreezeCreated: false, hundredPercentRolloutCreated: false,
      productionDeploymentIntroduced: false, realNotificationsSent: true,
      liveAiCallIntroduced: false, liveSchoolConnectorWriteIntroduced: false,
      productionDataMutationExecuted: false, rawPrivateDataStored: false,
      controlledLimitedRolloutCreated: true,
      contractsCreatedOrUpdated: true, validationCreatedOrUpdated: true,
      repositoryCreatedOrUpdated: true, servicesCreatedOrUpdated: true,
      routesCreatedOrUpdated: true, routesMountedOrDirectlyTested: true,
      verifiedSchoolContextRequired: true, task033AcceptanceRequired: true,
      rolloutEnvironmentGatePassed: true, limitedRolloutConfigPassed: true,
      rolloutCapGatePassed: true, expandedCohortEligibilityPassed: true,
      staffReadinessPassed: true, learnerNoticeReadinessPassed: true,
      controlledRolloutStateMachinePassed: true, controlledRolloutEventIntakePassed: true,
      expandedRuntimeGuardPassed: true, healthBudgetEscalationPassed: true,
      incidentEscalationBridgePassed: true, rollbackProtectionPassed: true,
      privacyReviewPassed: true, contentGovernanceReviewPassed: true,
      socraticIntegrityReviewPassed: true, deenBoundaryReviewPassed: true,
      schoolIdentityReviewPassed: true, crossSchoolDenialReviewPassed: true,
      safeRolloutReadModelPassed: true, evidenceLedgerPassed: true,
      diagnosticsPassed: true, postLimitedRolloutDecisionPassed: true,
      reportPassed: true,
      task034FocusedTestsRun: true, task034FocusedTestsPassed: true,
      task034FocusedTestFiles: 25, task034FocusedTestsPassedCount: 25,
      task034FocusedTestsFailedCount: 0,
      task020To033RegressionRun: true, task020To033RegressionPassed: true,
      phase3RegressionRun: true, phase3RegressionPassed: true,
      fullBackendSuiteRun: true, fullBackendSuitePassed: true,
      fullBackendSuiteFailedFiles: [], fullBackendSuiteFailedTests: [],
      prismaValidateRun: true, prismaValidatePassed: true,
      prismaGenerateRun: true, prismaGeneratePassed: true,
      backendBuildRun: true, backendBuildPassed: true,
      backendTypecheckRun: true, backendTypecheckPassed: true,
      task034VerificationScriptRun: true, task034VerificationScriptPassed: true,
      privacyScanRun: true, privacyScanPassed: true,
      noProductionMutationScanRun: true, noProductionMutationScanPassed: true,
      noLiveConnectorAiScanRun: true, noLiveConnectorAiScanPassed: true,
      noLiveNotificationScanRun: true, noLiveNotificationScanPassed: true,
      noFrontendUiScanRun: true, noFrontendUiScanPassed: true,
      noTask035ToTask040ScanRun: true, noTask035ToTask040ScanPassed: true,
      noFalsePassScanRun: true, noFalsePassScanPassed: true,
      safeToStartTask035: false, safeToStartTask040: false,
      verdict: 'TASK_034_PASS_SAFE_TO_START_TASK_035',
      commandsRun: [], filesCreated: [], filesModified: [],
      filesStaged: [], filesIntentionallyNotStaged: [],
      remainingBlockers: [], generatedAt: 'ts',
    };
    const result = validateTask034ReportTruth(base);
    expect(result.ok).toBe(false);
    expect(result.reasonCodes).toContain('realNotificationsSent_not_false');
  });

  it('safeToStartTask035 not false fails', () => {
    const base = {
      taskId: 'task-034', scope: 'controlled-limited-rollout',
      task033DependencyCommit: '276445d', task033DependencyVerified: true,
      task034Started: false, task035Started: false, task040Started: false,
      frontendUiCreated: false, schoolWideLaunchCreated: false,
      backendFreezeCreated: false, hundredPercentRolloutCreated: false,
      productionDeploymentIntroduced: false, realNotificationsSent: false,
      liveAiCallIntroduced: false, liveSchoolConnectorWriteIntroduced: false,
      productionDataMutationExecuted: false, rawPrivateDataStored: false,
      controlledLimitedRolloutCreated: true,
      contractsCreatedOrUpdated: true, validationCreatedOrUpdated: true,
      repositoryCreatedOrUpdated: true, servicesCreatedOrUpdated: true,
      routesCreatedOrUpdated: true, routesMountedOrDirectlyTested: true,
      verifiedSchoolContextRequired: true, task033AcceptanceRequired: true,
      rolloutEnvironmentGatePassed: true, limitedRolloutConfigPassed: true,
      rolloutCapGatePassed: true, expandedCohortEligibilityPassed: true,
      staffReadinessPassed: true, learnerNoticeReadinessPassed: true,
      controlledRolloutStateMachinePassed: true, controlledRolloutEventIntakePassed: true,
      expandedRuntimeGuardPassed: true, healthBudgetEscalationPassed: true,
      incidentEscalationBridgePassed: true, rollbackProtectionPassed: true,
      privacyReviewPassed: true, contentGovernanceReviewPassed: true,
      socraticIntegrityReviewPassed: true, deenBoundaryReviewPassed: true,
      schoolIdentityReviewPassed: true, crossSchoolDenialReviewPassed: true,
      safeRolloutReadModelPassed: true, evidenceLedgerPassed: true,
      diagnosticsPassed: true, postLimitedRolloutDecisionPassed: true,
      reportPassed: true,
      task034FocusedTestsRun: true, task034FocusedTestsPassed: true,
      task034FocusedTestFiles: 25, task034FocusedTestsPassedCount: 25,
      task034FocusedTestsFailedCount: 0,
      task020To033RegressionRun: true, task020To033RegressionPassed: true,
      phase3RegressionRun: true, phase3RegressionPassed: true,
      fullBackendSuiteRun: true, fullBackendSuitePassed: true,
      fullBackendSuiteFailedFiles: [], fullBackendSuiteFailedTests: [],
      prismaValidateRun: true, prismaValidatePassed: true,
      prismaGenerateRun: true, prismaGeneratePassed: true,
      backendBuildRun: true, backendBuildPassed: true,
      backendTypecheckRun: true, backendTypecheckPassed: true,
      task034VerificationScriptRun: true, task034VerificationScriptPassed: true,
      privacyScanRun: true, privacyScanPassed: true,
      noProductionMutationScanRun: true, noProductionMutationScanPassed: true,
      noLiveConnectorAiScanRun: true, noLiveConnectorAiScanPassed: true,
      noLiveNotificationScanRun: true, noLiveNotificationScanPassed: true,
      noFrontendUiScanRun: true, noFrontendUiScanPassed: true,
      noTask035ToTask040ScanRun: true, noTask035ToTask040ScanPassed: true,
      noFalsePassScanRun: true, noFalsePassScanPassed: true,
      safeToStartTask035: false, safeToStartTask040: false,
      verdict: 'TASK_034_PASS_SAFE_TO_START_TASK_035',
      commandsRun: [], filesCreated: [], filesModified: [],
      filesStaged: [], filesIntentionallyNotStaged: [],
      remainingBlockers: [], generatedAt: 'ts',
    };
    const result = validateTask034ReportTruth({ ...base, task034Started: true });
    expect(result.ok).toBe(false);
    expect(result.reasonCodes).toContain('task034Started_not_false');
  });

  it('liveAiCallIntroduced true fails', () => {
    const base = {
      taskId: 'task-034', scope: 'controlled-limited-rollout',
      task033DependencyCommit: '276445d', task033DependencyVerified: true,
      task034Started: false, task035Started: false, task040Started: false,
      frontendUiCreated: false, schoolWideLaunchCreated: false,
      backendFreezeCreated: false, hundredPercentRolloutCreated: false,
      productionDeploymentIntroduced: false, realNotificationsSent: false,
      liveAiCallIntroduced: true, liveSchoolConnectorWriteIntroduced: false,
      productionDataMutationExecuted: false, rawPrivateDataStored: false,
      controlledLimitedRolloutCreated: true,
      contractsCreatedOrUpdated: true, validationCreatedOrUpdated: true,
      repositoryCreatedOrUpdated: true, servicesCreatedOrUpdated: true,
      routesCreatedOrUpdated: true, routesMountedOrDirectlyTested: true,
      verifiedSchoolContextRequired: true, task033AcceptanceRequired: true,
      rolloutEnvironmentGatePassed: true, limitedRolloutConfigPassed: true,
      rolloutCapGatePassed: true, expandedCohortEligibilityPassed: true,
      staffReadinessPassed: true, learnerNoticeReadinessPassed: true,
      controlledRolloutStateMachinePassed: true, controlledRolloutEventIntakePassed: true,
      expandedRuntimeGuardPassed: true, healthBudgetEscalationPassed: true,
      incidentEscalationBridgePassed: true, rollbackProtectionPassed: true,
      privacyReviewPassed: true, contentGovernanceReviewPassed: true,
      socraticIntegrityReviewPassed: true, deenBoundaryReviewPassed: true,
      schoolIdentityReviewPassed: true, crossSchoolDenialReviewPassed: true,
      safeRolloutReadModelPassed: true, evidenceLedgerPassed: true,
      diagnosticsPassed: true, postLimitedRolloutDecisionPassed: true,
      reportPassed: true,
      task034FocusedTestsRun: true, task034FocusedTestsPassed: true,
      task034FocusedTestFiles: 25, task034FocusedTestsPassedCount: 25,
      task034FocusedTestsFailedCount: 0,
      task020To033RegressionRun: true, task020To033RegressionPassed: true,
      phase3RegressionRun: true, phase3RegressionPassed: true,
      fullBackendSuiteRun: true, fullBackendSuitePassed: true,
      fullBackendSuiteFailedFiles: [], fullBackendSuiteFailedTests: [],
      prismaValidateRun: true, prismaValidatePassed: true,
      prismaGenerateRun: true, prismaGeneratePassed: true,
      backendBuildRun: true, backendBuildPassed: true,
      backendTypecheckRun: true, backendTypecheckPassed: true,
      task034VerificationScriptRun: true, task034VerificationScriptPassed: true,
      privacyScanRun: true, privacyScanPassed: true,
      noProductionMutationScanRun: true, noProductionMutationScanPassed: true,
      noLiveConnectorAiScanRun: true, noLiveConnectorAiScanPassed: true,
      noLiveNotificationScanRun: true, noLiveNotificationScanPassed: true,
      noFrontendUiScanRun: true, noFrontendUiScanPassed: true,
      noTask035ToTask040ScanRun: true, noTask035ToTask040ScanPassed: true,
      noFalsePassScanRun: true, noFalsePassScanPassed: true,
      safeToStartTask035: false, safeToStartTask040: false,
      verdict: 'TASK_034_PASS_SAFE_TO_START_TASK_035',
      commandsRun: [], filesCreated: [], filesModified: [],
      filesStaged: [], filesIntentionallyNotStaged: [],
      remainingBlockers: [], generatedAt: 'ts',
    };
    const result = validateTask034ReportTruth(base);
    expect(result.ok).toBe(false);
    expect(result.reasonCodes).toContain('liveAiCallIntroduced_not_false');
  });
});
