// Per-route hang isolation. One route per run via ROUTE env.
const t0 = Date.now();
const log = (m: string) => console.log('+' + (Date.now() - t0) + 'ms ' + m);
setTimeout(() => { console.log('TIMEOUT-EXIT'); process.exit(2); }, 100000).unref();
(async () => {
  const express = (await import('express')).default;
  const request = (await import('supertest')).default;
  const jwt = (await import('jsonwebtoken')).default;
  const { requestIdMiddleware } = await import('../../src/middleware/requestId');
  const { schoolAuthMiddleware } = await import('../../src/middleware/schoolAuthMiddleware');
  const { requireVerifiedSchoolContext } = await import('../../src/middleware/schoolContextGuardMiddleware');
  const { backpressureMiddleware } = await import('../../src/middleware/task019BackpressureMiddleware');
  const { rateLimitMiddleware } = await import('../../src/middleware/task019RateLimitMiddleware');
  const healthRoutes = (await import('../../src/routes/health')).default;
  log('imports done');
  const app = express();
  app.use(express.json({ limit: '1mb' }));
  app.use(requestIdMiddleware);
  app.use('/api/health', healthRoutes);
  app.use('/api/open', schoolAuthMiddleware, (_req: any, res: any) => res.json({ ok: true }));
  app.use('/api/guarded', schoolAuthMiddleware, requireVerifiedSchoolContext, backpressureMiddleware, rateLimitMiddleware, (_req: any, res: any) => res.json({ ok: true }));
  const which = process.env.ROUTE || 'health';
  const token = jwt.sign({ userId: 'stu-1', schoolId: 'school-a', role: 'student' }, String(process.env.JWT_SECRET), { expiresIn: '5m' });
  log('sending ' + which);
  let r: any;
  if (which === 'health') r = await request(app).get('/api/health');
  else if (which === 'open-noauth') r = await request(app).get('/api/open');
  else if (which === 'open-auth') r = await request(app).get('/api/open').set('Authorization', 'Bearer ' + token);
  else if (which === 'guarded') r = await request(app).get('/api/guarded').set('Authorization', 'Bearer ' + token);
  log(which + ' status=' + r.status + ' body=' + JSON.stringify(r.body).slice(0, 300));
  process.exit(0);
})().catch((e) => { console.log('FAIL ' + (e && e.stack)); process.exit(1); });
