// ─────────────────────────────────────────────────────────────
// Steadfast AI — Task 020 Data Classification Registry Service v1
// Classifies backend data types by sensitivity, owner, visibility,
// retention category, export eligibility, and deletion restrictions.
// ─────────────────────────────────────────────────────────────

import type {
  DataCategory,
  DataClassificationEntry,
  DataClassificationSummary,
  SensitivityLevel,
  OwnerType,
  RetentionCategory,
} from '../contracts/task020GovernanceContracts';

const CLASSIFICATION_REGISTRY: Record<DataCategory, DataClassificationEntry> = {
  learner_identity: {
    category: 'learner_identity',
    sensitivityLevel: 'high',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin', 'internal_operator'],
    teacherVisible: false,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: true,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: true,
    reasonCodes: ['identity-pii-provisioned'],
  },
  school_identity: {
    category: 'school_identity',
    sensitivityLevel: 'medium',
    ownerType: 'school',
    allowedRoles: ['teacher', 'school_admin', 'system_admin', 'internal_operator'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: false,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: false,
    reasonCodes: ['school-identity-operational'],
  },
  class_roster_scope: {
    category: 'class_roster_scope',
    sensitivityLevel: 'medium',
    ownerType: 'school',
    allowedRoles: ['teacher', 'school_admin', 'safeguarding_officer', 'system_admin', 'internal_operator'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: false,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: false,
    reasonCodes: ['class-roster-operational'],
  },
  tutor_session_state: {
    category: 'tutor_session_state',
    sensitivityLevel: 'medium',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'active_learning',
    redactionRequired: false,
    reasonCodes: ['session-state-metadata'],
  },
  conversation_message: {
    category: 'conversation_message',
    sensitivityLevel: 'high',
    ownerType: 'learner',
    allowedRoles: ['learner', 'safeguarding_officer', 'system_admin'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: true,
    safeguardingRestricted: true,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: true,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'conversation_archive',
    redactionRequired: true,
    reasonCodes: ['raw-chat-restricted', 'safeguarding-review-only'],
  },
  conversation_archive: {
    category: 'conversation_archive',
    sensitivityLevel: 'high',
    ownerType: 'learner',
    allowedRoles: ['learner', 'safeguarding_officer', 'system_admin'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: true,
    safeguardingRestricted: true,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: true,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'conversation_archive',
    redactionRequired: true,
    reasonCodes: ['archive-raw-restricted', 'safeguarding-review-only'],
  },
  safe_memory_summary: {
    category: 'safe_memory_summary',
    sensitivityLevel: 'medium',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'safe_memory_summary',
    redactionRequired: false,
    reasonCodes: ['safe-memory-summary-privacy-safe'],
  },
  practice_attempt: {
    category: 'practice_attempt',
    sensitivityLevel: 'medium',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: false,
    reasonCodes: ['practice-attempt-summary-safe'],
  },
  learning_evidence: {
    category: 'learning_evidence',
    sensitivityLevel: 'medium',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: false,
    reasonCodes: ['learning-evidence-summary-safe'],
  },
  mastery_snapshot: {
    category: 'mastery_snapshot',
    sensitivityLevel: 'low',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: false,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: false,
    reasonCodes: ['mastery-aggregate-safe'],
  },
  revision_item: {
    category: 'revision_item',
    sensitivityLevel: 'low',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: false,
    reasonCodes: ['revision-item-safe'],
  },
  spaced_review_item: {
    category: 'spaced_review_item',
    sensitivityLevel: 'low',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'active_learning',
    redactionRequired: false,
    reasonCodes: ['spaced-review-item-safe'],
  },
  teacher_safe_summary: {
    category: 'teacher_safe_summary',
    sensitivityLevel: 'low',
    ownerType: 'shared',
    allowedRoles: ['teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'operational_audit',
    redactionRequired: false,
    reasonCodes: ['teacher-summary-safe'],
  },
  learner_preference_feedback: {
    category: 'learner_preference_feedback',
    sensitivityLevel: 'low',
    ownerType: 'learner',
    allowedRoles: ['learner', 'system_admin'],
    teacherVisible: false,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'active_learning',
    redactionRequired: false,
    reasonCodes: ['learner-preference-safe'],
  },
  adaptive_profile: {
    category: 'adaptive_profile',
    sensitivityLevel: 'low',
    ownerType: 'learner',
    allowedRoles: ['learner', 'system_admin'],
    teacherVisible: false,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'active_learning',
    redactionRequired: false,
    reasonCodes: ['adaptive-profile-safe'],
  },
  challenge_record: {
    category: 'challenge_record',
    sensitivityLevel: 'medium',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'long_term_learning_evidence',
    redactionRequired: false,
    reasonCodes: ['challenge-record-safe'],
  },
  remediation_path: {
    category: 'remediation_path',
    sensitivityLevel: 'medium',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'active_learning',
    redactionRequired: false,
    reasonCodes: ['remediation-path-safe'],
  },
  difficulty_calibration: {
    category: 'difficulty_calibration',
    sensitivityLevel: 'low',
    ownerType: 'learner',
    allowedRoles: ['learner', 'teacher', 'school_admin', 'system_admin'],
    teacherVisible: true,
    adminVisible: true,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: true,
    deleteEligibility: true,
    retentionCategory: 'active_learning',
    redactionRequired: false,
    reasonCodes: ['difficulty-calibration-safe'],
  },
  audit_event: {
    category: 'audit_event',
    sensitivityLevel: 'medium',
    ownerType: 'system',
    allowedRoles: ['system_admin', 'internal_operator', 'safeguarding_officer'],
    teacherVisible: false,
    adminVisible: true,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: false,
    retentionCategory: 'security_audit',
    redactionRequired: false,
    reasonCodes: ['audit-metadata-safe'],
  },
  operational_telemetry: {
    category: 'operational_telemetry',
    sensitivityLevel: 'low',
    ownerType: 'system',
    allowedRoles: ['system_admin', 'internal_operator'],
    teacherVisible: false,
    adminVisible: true,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'diagnostic_telemetry',
    redactionRequired: false,
    reasonCodes: ['telemetry-safe'],
  },
  rate_limit_record: {
    category: 'rate_limit_record',
    sensitivityLevel: 'low',
    ownerType: 'system',
    allowedRoles: ['system_admin', 'internal_operator'],
    teacherVisible: false,
    adminVisible: true,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'rate_limit_short_lived',
    redactionRequired: false,
    reasonCodes: ['rate-limit-record-safe'],
  },
  safeguarding_metadata: {
    category: 'safeguarding_metadata',
    sensitivityLevel: 'critical',
    ownerType: 'learner',
    allowedRoles: ['safeguarding_officer', 'system_admin'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: false,
    safeguardingRestricted: true,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: false,
    retentionCategory: 'safeguarding_restricted',
    redactionRequired: true,
    reasonCodes: ['safeguarding-restricted-metadata-only'],
  },
  deen_sensitive_metadata: {
    category: 'deen_sensitive_metadata',
    sensitivityLevel: 'high',
    ownerType: 'learner',
    allowedRoles: ['learner', 'safeguarding_officer', 'system_admin'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: true,
    safeguardingRestricted: false,
    deenSensitive: true,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'safeguarding_restricted',
    redactionRequired: true,
    reasonCodes: ['deen-sensitive-metadata-restricted'],
  },
  ai_prompt_metadata: {
    category: 'ai_prompt_metadata',
    sensitivityLevel: 'high',
    ownerType: 'system',
    allowedRoles: ['system_admin', 'internal_operator'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: true,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'diagnostic_telemetry',
    redactionRequired: true,
    reasonCodes: ['prompt-metadata-internal-only'],
  },
  provider_response_metadata: {
    category: 'provider_response_metadata',
    sensitivityLevel: 'high',
    ownerType: 'system',
    allowedRoles: ['system_admin', 'internal_operator'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: true,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'diagnostic_telemetry',
    redactionRequired: true,
    reasonCodes: ['provider-response-internal-only'],
  },
  idempotency_record: {
    category: 'idempotency_record',
    sensitivityLevel: 'low',
    ownerType: 'system',
    allowedRoles: ['system_admin'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: false,
    safeguardingRestricted: false,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: true,
    retentionCategory: 'idempotency_short_lived',
    redactionRequired: false,
    reasonCodes: ['idempotency-record-short-lived'],
  },
  unknown: {
    category: 'unknown',
    sensitivityLevel: 'high',
    ownerType: 'system',
    allowedRoles: ['system_admin'],
    teacherVisible: false,
    adminVisible: false,
    learnerVisible: false,
    safeguardingRestricted: true,
    deenSensitive: false,
    containsPII: false,
    containsRawContent: false,
    exportEligibility: false,
    deleteEligibility: false,
    retentionCategory: 'security_audit',
    redactionRequired: true,
    reasonCodes: ['unknown-category-deny-by-default'],
  },
};

export class DataClassificationRegistryService {
  getClassification(category: DataCategory): DataClassificationEntry | null {
    const entry = CLASSIFICATION_REGISTRY[category];
    if (!entry) return null;
    return { ...entry };
  }

  getAllCategories(): DataCategory[] {
    return Object.keys(CLASSIFICATION_REGISTRY) as DataCategory[];
  }

  getAllClassifications(): DataClassificationEntry[] {
    return Object.values(CLASSIFICATION_REGISTRY).map(e => ({ ...e }));
  }

  getSummary(category: DataCategory): DataClassificationSummary | null {
    const entry = this.getClassification(category);
    if (!entry) return null;
    return {
      category: entry.category,
      sensitivityLevel: entry.sensitivityLevel,
      ownerType: entry.ownerType,
      visibility: {
        teacher: entry.teacherVisible,
        admin: entry.adminVisible,
        learner: entry.learnerVisible,
        safeguardingOnly: entry.safeguardingRestricted,
      },
      exportEligibility: entry.exportEligibility,
      deleteEligibility: entry.deleteEligibility,
      retentionCategory: entry.retentionCategory,
      redactionRequired: entry.redactionRequired,
      reasonCodes: entry.reasonCodes,
    };
  }

  getAllSummaries(): DataClassificationSummary[] {
    return this.getAllCategories()
      .map(cat => this.getSummary(cat))
      .filter((s): s is DataClassificationSummary => s !== null);
  }

  isKnownCategory(category: string): category is DataCategory {
    return category in CLASSIFICATION_REGISTRY;
  }

  getRetentionCategory(category: DataCategory): RetentionCategory | null {
    const entry = this.getClassification(category);
    return entry ? entry.retentionCategory : null;
  }

  isExportEligible(category: DataCategory): boolean {
    const entry = this.getClassification(category);
    return entry ? entry.exportEligibility : false;
  }

  isDeleteEligible(category: DataCategory): boolean {
    const entry = this.getClassification(category);
    return entry ? entry.deleteEligibility : false;
  }
}

export const dataClassificationRegistryService = new DataClassificationRegistryService();
