import { AssessmentPolicyFamily, AssessmentPolicyDecision } from '../../contracts/assessmentPolicyContracts';
import { MarkingRunStatus } from '../contracts/markingContracts';

export const MARKING_POLICY_DEFAULTS: Record<string, {
  missingDecision: AssessmentPolicyDecision;
  defaultBlockedStatus: string;
}> = {
  MARKING_RUN_CREATION: {
    missingDecision: {
      decisionId: 'policy-default-marking-run-creation-missing',
      policyFamily: 'MARKING_RUN_CREATION',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Marking run creation is not configured. Please contact your system administrator.',
      missingPolicyKeys: ['marking.run.creation'],
      requiredOwner: 'school_admin',
      blockedOperation: 'createMarkingRun',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
  DETERMINISTIC_MARKING: {
    missingDecision: {
      decisionId: 'policy-default-deterministic-marking-missing',
      policyFamily: 'DETERMINISTIC_MARKING',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Deterministic marking is not configured for this school.',
      missingPolicyKeys: ['marking.deterministic'],
      requiredOwner: 'school_admin',
      blockedOperation: 'deterministicMark',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
  RUBRIC_MARKING: {
    missingDecision: {
      decisionId: 'policy-default-rubric-marking-missing',
      policyFamily: 'RUBRIC_MARKING',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Rubric-assisted marking is not configured. Routing to teacher review.',
      missingPolicyKeys: ['marking.rubric'],
      requiredOwner: 'school_admin',
      blockedOperation: 'rubricMark',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
  TEACHER_REVIEW: {
    missingDecision: {
      decisionId: 'policy-default-teacher-review-missing',
      policyFamily: 'TEACHER_REVIEW',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Teacher review workflow is not configured. Review resolution is blocked.',
      missingPolicyKeys: ['teacher.review'],
      requiredOwner: 'school_admin',
      blockedOperation: 'resolveTeacherReview',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
  TEACHER_OVERRIDE: {
    missingDecision: {
      decisionId: 'policy-default-teacher-override-missing',
      policyFamily: 'TEACHER_OVERRIDE',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Teacher override is not configured for this school.',
      missingPolicyKeys: ['teacher.override'],
      requiredOwner: 'school_admin',
      blockedOperation: 'teacherOverride',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
  MODERATION_DECISION: {
    missingDecision: {
      decisionId: 'policy-default-moderation-decision-missing',
      policyFamily: 'MODERATION_DECISION',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Moderation decision workflow is not configured.',
      missingPolicyKeys: ['moderation.decision'],
      requiredOwner: 'school_admin',
      blockedOperation: 'createModerationDecision',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
  STUDENT_MARK_CHALLENGE: {
    missingDecision: {
      decisionId: 'policy-default-student-mark-challenge-missing',
      policyFamily: 'STUDENT_MARK_CHALLENGE',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Student mark challenge is not configured for this school.',
      missingPolicyKeys: ['student.challenge'],
      requiredOwner: 'school_admin',
      blockedOperation: 'submitChallenge',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
  SCORING_SUGGESTION: {
    missingDecision: {
      decisionId: 'policy-default-scoring-suggestion-missing',
      policyFamily: 'SCORING_SUGGESTION',
      status: 'MISSING',
      allowed: true,
      reasonCode: 'POLICY_MISSING',
      safeMessage: 'Scoring suggestions are not configured for this school.',
      missingPolicyKeys: ['scoring.suggestion'],
      requiredOwner: 'school_admin',
      blockedOperation: 'createSuggestion',
      policyVersionRef: '0.0.0',
      createdAt: new Date().toISOString(),
    },
    defaultBlockedStatus: 'blocked',
  },
};
