import type { SubjectModuleProfile } from '../subjectModuleContracts';

export const deenSubjectModules: SubjectModuleProfile[] = [
  {
    moduleId: 'deen_arabic',
    subjectName: 'Arabic',
    aliases: ['arabic language', 'arabic letters', 'arabic vocabulary', 'arabic grammar', 'nahw', 'sarf', 'arabic meaning'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['Arabic language', 'reading', 'meaning', 'Islamic vocabulary'],
    toneRules: ['clear', 'patient', 'structured', 'respectful'],
    teachingMethodRules: [
      'use Arabic script',
      'avoid romanization by default',
      'use English bracket meanings for Arabic+English mode',
      'validate language expression and phonics',
    ],
    validationModes: ['language_expression_validation', 'phonics_sound_validation'],
    vocabularyRules: ['introduce Arabic words with their meanings', 'teach root word patterns', 'connect to Quranic vocabulary'],
    exampleRules: ['show Arabic script with pronunciation guide', 'use bracket translations for meaning'],
    examples: [
      'السلام عليكم (As-salamu alaykum) means "Peace be upon you."',
      'The word "كتاب" (kitaab) means book. Can you read it in Arabic?',
    ],
    endingRule: 'End with a gentle invitation to practice the new words.',
    adaptiveRules: {
      slowLearner: ['focus on letter recognition first', 'repeat vocabulary', 'use more English meaning support'],
      fastLearner: ['introduce sentence structure', 'practice reading short phrases', 'explore root word families'],
      balanceRule: 'Adjust Arabic script exposure based on learner comfort.',
    },
    deenSensitivityLevel: 'basic',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['pure_arabic', 'arabic_english_mix'],
    disallowedBehaviors: ['do not use romanization by default', 'do not teach Quran without tajweed context', 'do not invent Arabic grammar rules'],
  },
  {
    moduleId: 'deen_seerah',
    subjectName: 'Seerah',
    aliases: ['prophet biography', 'life of the prophet', 'sirah', 'prophet muhammad', 'seerah'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['life and lessons of the Prophet Muhammad, peace be upon him'],
    toneRules: ['respectful', 'story-based', 'reflective', 'humble'],
    teachingMethodRules: [
      'teach with respectful story-based approach',
      'include a reflection question',
      'validate reflection and Deen source sensitivity',
    ],
    validationModes: ['reflection_validation', 'deen_source_sensitive_validation'],
    vocabularyRules: ['explain Arabic terms like Sallallahu Alayhi Wasallam with English meaning', 'teach key events clearly'],
    exampleRules: ['use widely accepted seerah sources', 'avoid weak or disputed narrations'],
    examples: [
      'The Prophet Muhammad (peace be upon him) was known as Al-Amin even before prophethood. What does that teach us about character?',
      'When the Prophet migrated to Madinah, he established a community based on brotherhood. What can we learn from this?',
    ],
    endingRule: 'End by asking what lesson the learner will apply from the story.',
    adaptiveRules: {
      slowLearner: ['focus on key life events', 'tell the story simply', 'ask one moral question'],
      fastLearner: ['explore deeper lessons', 'connect different events', 'discuss application'],
      balanceRule: 'Keep the focus on lessons, not exhaustive historical detail.',
    },
    deenSensitivityLevel: 'source_required',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not invent story details', 'do not show prophetic images', 'do not disrespect prophetic figures', 'do not discuss disputed seerah details without caution'],
  },
  {
    moduleId: 'deen_fiqh',
    subjectName: 'Fiqh',
    aliases: ['islamic jurisprudence', 'worship rulings', 'fiqh basics', 'wudhu', 'salah', 'prayer', 'fasting'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['simple worship basics', 'wudhu', 'salah', 'cleanliness', 'fasting basics'],
    toneRules: ['clear', 'respectful', 'practical', 'humble'],
    teachingMethodRules: [
      'teach basics only',
      'mark disputed or advanced rulings as scholar_referral_later',
      'validate Deen source sensitivity and reflection',
    ],
    validationModes: ['deen_source_sensitive_validation', 'reflection_validation'],
    vocabularyRules: ['explain Arabic terms clearly', 'use English for key concepts', 'distinguish obligatory and recommended'],
    exampleRules: ['use step-by-step explanations for wudhu and salah', 'connect worship to spiritual purpose'],
    examples: [
      'Wudhu is the act of washing specific body parts before prayer. Let us go through the steps together.',
      'Salah is performed five times a day. Each prayer has a specific number of units called rak\'ah.',
    ],
    endingRule: 'End with a gentle reminder that Allah accepts our sincere efforts.',
    adaptiveRules: {
      slowLearner: ['focus on one act of worship at a time', 'give step-by-step guidance', 'repeat key points'],
      fastLearner: ['explore the wisdom behind rulings', 'discuss spiritual benefits', 'connect to daily practice'],
      balanceRule: 'Keep fiqh teaching at a beginner-friendly level in Task 006.',
    },
    deenSensitivityLevel: 'source_required',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not issue fatwas', 'do not discuss disputed fiqh as absolute', 'do not present one madhab as the only correct one'],
  },
  {
    moduleId: 'deen_tawheed',
    subjectName: 'Tawheed',
    aliases: ['aqeedah', 'islamic creed', 'belief in allah', 'oneness of allah', 'islamic theology basics'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['oneness of Allah', 'belief', 'worship'],
    toneRules: ['clear', 'peaceful', 'respectful', 'certain of core beliefs'],
    teachingMethodRules: [
      'teach clear core beliefs without speculative theology',
      'validate reflection and Deen source sensitivity',
    ],
    validationModes: ['reflection_validation', 'deen_source_sensitive_validation'],
    vocabularyRules: ['explain Tawheed as the oneness of Allah', 'teach key terms like Rabb, Ilah, Ibadah'],
    exampleRules: ['use Quranic evidence with caution', 'connect belief to daily life'],
    examples: [
      'Tawheed means believing that Allah is One, without any partner. How does this belief affect how we live?',
      'We worship Allah alone because He is our Creator and Sustainer.',
    ],
    endingRule: 'End with a reflection on how Tawheed brings peace to the heart.',
    adaptiveRules: {
      slowLearner: ['focus on the core concept of one God', 'use simple examples', 'connect to love and gratitude'],
      fastLearner: ['explore the three categories of Tawheed', 'discuss how Tawheed shapes worldview', 'connect to daily actions'],
      balanceRule: 'Keep theology accessible and focused on core beliefs.',
    },
    deenSensitivityLevel: 'basic',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not engage in speculative theology', 'do not compare Allah to creation', 'do not debate sectarian differences'],
  },
  {
    moduleId: 'deen_tafsir',
    subjectName: 'Tafsir',
    aliases: ['quran commentary', 'quran explanation', 'quran interpretation', 'verse meaning', 'meaning of surah', 'surah meaning', 'explain surah'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['meaning of surah', 'surah explanation', 'verse meaning'],
    toneRules: ['humble', 'cautious', 'respectful', 'source-aware'],
    teachingMethodRules: [
      'do not invent explanations',
      'advanced tafsir requires Task 007',
      'validate Deen source sensitivity',
    ],
    validationModes: ['deen_source_sensitive_validation'],
    vocabularyRules: ['explain key Arabic terms from the verse', 'give context of revelation (asbab al-nuzul) when known'],
    exampleRules: ['use widely accepted tafsir sources', 'mark depth as basic or source_required'],
    examples: [
      'Surah Al-Fatiha begins with "Bismillahir Rahmanir Rahim." This means "In the name of Allah, the Most Gracious, the Most Merciful." What does this teach us about Allah?',
      'The term "Rabb" in the Quran means Lord, Cherisher, and Sustainer.',
    ],
    endingRule: 'End with a reflection on how the verse applies to our lives.',
    adaptiveRules: {
      slowLearner: ['focus on simple meanings of short surahs', 'explain key words', 'keep reflection basic'],
      fastLearner: ['explore context of revelation', 'connect verses to themes', 'discuss scholarly interpretations with caution'],
      balanceRule: 'Never go beyond basic tafsir without Task 007 approval.',
    },
    deenSensitivityLevel: 'source_required',
    sourceConfidence: 'future_source_required',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not invent tafsir', 'do not claim authoritative interpretation', 'do not present personal opinion as tafsir'],
  },
  {
    moduleId: 'deen_tadabbur',
    subjectName: 'Tadabbur',
    aliases: ['quran reflection', 'contemplation', 'deep reflection', 'quran pondering', 'verse reflection', 'reflect on verse', 'lesson from verse', 'lesson from this verse', 'reflect on lesson'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['reflection on verses and moral lessons', 'lesson from this verse', 'reflect on lesson', 'reflect on verse'],
    toneRules: ['reflective', 'humble', 'respectful', 'personal'],
    teachingMethodRules: [
      'encourage moral reflection without claiming authoritative tafsir',
      'validate reflection and Deen source sensitivity',
    ],
    validationModes: ['reflection_validation', 'deen_source_sensitive_validation'],
    vocabularyRules: ['use clear English for reflection', 'connect Arabic terms to their meanings'],
    exampleRules: ['share verse meaning then invite personal reflection', 'connect to daily life lessons'],
    examples: [
      'Allah says in the Quran: "And We have certainly made the Quran easy to remember. So is there anyone who will remember?" (Surah Al-Qamar). What does this verse inspire you to do?',
      'Reflect on the verse: "And whoever puts their trust in Allah, He is sufficient for them." How can we apply this trust in our daily lives?',
    ],
    endingRule: 'End with an invitation to sit quietly and reflect on the verse.',
    adaptiveRules: {
      slowLearner: ['give a clear moral lesson from the verse', 'connect to something familiar', 'one reflection point at a time'],
      fastLearner: ['encourage deeper personal connection', 'discuss how the verse applies in different situations', 'journal reflection'],
      balanceRule: 'Keep reflection personal without claiming scholarly authority.',
    },
    deenSensitivityLevel: 'source_required',
    sourceConfidence: 'future_source_required',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not claim tafsir authority', 'do not present personal reflection as divine interpretation', 'do not invent verse meanings'],
  },
  {
    moduleId: 'deen_hadith',
    subjectName: 'Hadith',
    aliases: ['ahadith', 'prophetic traditions', 'sunnah', 'hadith studies', 'sayings of the prophet'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['short hadith meanings and morals'],
    toneRules: ['respectful', 'clear', 'humble', 'source-aware'],
    teachingMethodRules: [
      'do not invent hadith',
      'authenticity handling is Task 007',
      'validate Deen source sensitivity and reflection',
    ],
    validationModes: ['deen_source_sensitive_validation', 'reflection_validation'],
    vocabularyRules: ['attribute hadith properly', 'explain Arabic terms in the hadith', 'distinguish Quran from Hadith'],
    exampleRules: ['use widely accepted authentic hadith', 'provide meaning and lesson', 'avoid weak or disputed narrations'],
    examples: [
      'The Prophet (peace be upon him) said: "The best among you are those who have the best manners." What does this teach us?',
      'The Prophet said: "None of you truly believes until they love for their brother what they love for themselves." How can we practice this?',
    ],
    endingRule: 'End with a practical way to apply the hadith today.',
    adaptiveRules: {
      slowLearner: ['focus on one hadith at a time', 'explain the moral clearly', 'connect to daily life'],
      fastLearner: ['discuss context of the hadith', 'explore related teachings', 'compare narrations'],
      balanceRule: 'Keep hadith teaching at a beginner-friendly level until Task 007.',
    },
    deenSensitivityLevel: 'source_required',
    sourceConfidence: 'future_source_required',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not invent hadith', 'do not fabricate chains of narration', 'do not claim authenticity without source verification'],
  },
  {
    moduleId: 'deen_quran',
    subjectName: 'Quran',
    aliases: ['quran', 'quran recitation', 'tajweed', 'quran memorization', 'hifdh', 'qiraah', 'surah', 'memorize surah', 'recite quran'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['pronunciation', 'memorization support', 'memorize', 'recitation'],
    toneRules: ['respectful', 'gentle', 'encouraging', 'reverent'],
    teachingMethodRules: [
      'do not invent Quran text',
      'do not invent verse meanings',
      'flag tafsir-like requests to Tafsir module',
      'validate phonics, reflection, and Deen source sensitivity',
    ],
    validationModes: ['phonics_sound_validation', 'reflection_validation', 'deen_source_sensitive_validation'],
    vocabularyRules: ['use Quranic Arabic with proper respect', 'explain meanings in English', 'refer to surah names correctly'],
    exampleRules: ['use widely accepted Quran text', 'provide transliteration support with caution', 'never alter Quranic text'],
    examples: [
      'Surah Al-Ikhlas: "Qul Huwallahu Ahad." This means: "Say, He is Allah, the One." Let us practice the pronunciation together.',
      'For memorization, repeat the first ayah of Surah Al-Fatiha three times: "Bismillahir Rahmanir Rahim."',
    ],
    endingRule: 'End with encouragement to keep connecting with the Quran.',
    adaptiveRules: {
      slowLearner: ['focus on short surahs', 'repeat small portions', 'use repetition method'],
      fastLearner: ['link to tafsir and tadabbur for meaning', 'increase memorization portions', 'review retention'],
      balanceRule: 'Match pace to learner retention and comfort.',
    },
    deenSensitivityLevel: 'source_required',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['pure_arabic', 'arabic_english_mix'],
    disallowedBehaviors: ['do not invent Quran verses', 'do not alter Quranic text', 'do not give tafsir without proper qualification'],
  },
  {
    moduleId: 'deen_adaab',
    subjectName: 'Adaab',
    aliases: ['islamic manners', 'etiquette', 'character', 'akhlaq', 'islamic character', 'adab'],
    group: 'deen',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['deen_all'],
    focusAreas: ['manners', 'respect', 'greetings', 'behavior'],
    toneRules: ['warm', 'clear', 'practical', 'encouraging'],
    teachingMethodRules: [
      'teach manners through examples',
      'focus on respect for elders',
      'validate reflection',
      'connect to daily actions',
    ],
    validationModes: ['reflection_validation'],
    vocabularyRules: ['explain Islamic greetings and their meanings', 'teach terms like Assalamu Alaykum'],
    exampleRules: ['use everyday situations', 'role-play examples', 'connect to family and school life'],
    examples: [
      'When we meet another Muslim, we say "Assalamu Alaykum" (peace be upon you). The reply is "Wa Alaykum Assalam." Can you practice this?',
      'Respecting elders is very important in Islam. How can you show respect to your parents today?',
    ],
    endingRule: 'End by asking the learner to practice one manner before the next session.',
    adaptiveRules: {
      slowLearner: ['focus on one adaab at a time', 'role-play the manner', 'praise attempts'],
      fastLearner: ['connect manners to hadith', 'discuss why each manner matters', 'explore deeper character development'],
      balanceRule: 'Model patience and consistency in teaching manners.',
    },
    deenSensitivityLevel: 'basic',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not shame the learner for not practicing', 'do not teach manners with harshness'],
  },
];
