import type { SubjectModuleProfile } from '../subjectModuleContracts';

export const generalEnrichmentSubjectModules: SubjectModuleProfile[] = [
  {
    moduleId: 'enrichment_critical_thinking',
    subjectName: 'Critical Thinking',
    aliases: ['logic', 'reasoning', 'thinking skills', 'critical analysis', 'questioning'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['logic', 'reasoning', 'questions', 'cause and effect'],
    toneRules: ['thoughtful', 'encouraging', 'open-ended', 'socratic'],
    teachingMethodRules: ['ask open-ended questions', 'challenge assumptions gently', 'validate reasoning clarity'],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['introduce terms like assumption, evidence, conclusion', 'use plain language'],
    exampleRules: ['use everyday scenarios', 'connect to school and home life'],
    examples: [
      'If all birds have wings and a penguin is a bird, does a penguin have wings? Why or why not?',
      'What evidence supports your conclusion? Can you think of an alternative explanation?',
    ],
    endingRule: 'End with a question that invites further curiosity.',
    adaptiveRules: {
      slowLearner: ['use concrete examples', 'give more time to think', 'prompt with simpler questions'],
      fastLearner: ['use abstract scenarios', 'encourage metacognition', 'explore logical fallacies'],
      balanceRule: 'Adjust question complexity to learner comfort.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not dismiss learner answers', 'do not make learner feel foolish for wrong answers'],
  },
  {
    moduleId: 'enrichment_problem_solving',
    subjectName: 'Problem Solving',
    aliases: ['solving problems', 'step by step', 'solutions', 'testing ideas', 'troubleshooting'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['breaking problems into steps', 'solutions', 'testing ideas'],
    toneRules: ['encouraging', 'structured', 'patient'],
    teachingMethodRules: ['guide step-by-step', 'celebrate process over answer', 'validate reasoning clarity'],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['teach terms like step, solution, test, alternative', 'use clear instructions'],
    exampleRules: ['use real-life problems', 'connect to school and home challenges'],
    examples: [
      'Let us break this problem into smaller steps. First, what do we know?',
      'What are three possible solutions? Let us test each one.',
    ],
    endingRule: 'End by acknowledging the effort put into solving.',
    adaptiveRules: {
      slowLearner: ['provide more structure', 'give example solutions first', 'celebrate small steps'],
      fastLearner: ['encourage multiple approaches', 'discuss trade-offs', 'explore efficiency'],
      balanceRule: 'Focus on process, not just the answer.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not give the answer immediately', 'do not discourage creative solutions'],
  },
  {
    moduleId: 'enrichment_character_moral_intelligence',
    subjectName: 'Character and Moral Intelligence',
    aliases: ['honesty', 'kindness', 'patience', 'responsibility', 'respect', 'humility', 'morals', 'values'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['honesty', 'kindness', 'patience', 'responsibility', 'respect', 'humility'],
    toneRules: ['warm', 'reflective', 'encouraging', 'respectful'],
    teachingMethodRules: ['teach through scenarios and stories', 'validate reflection', 'ask character-based questions'],
    validationModes: ['reflection_validation'],
    vocabularyRules: ['teach character trait names', 'connect to real-life examples'],
    exampleRules: ['use everyday moral dilemmas', 'share brief character stories'],
    examples: [
      'If you find a wallet on the playground, what should you do? Why?',
      'Being patient means waiting calmly. Can you think of a time when you were patient?',
    ],
    endingRule: 'End with a challenge to practice one character trait today.',
    adaptiveRules: {
      slowLearner: ['focus on one trait at a time', 'use clear examples', 'praise small efforts'],
      fastLearner: ['explore how traits interact', 'discuss how to handle peer pressure', 'reflect on personal growth'],
      balanceRule: 'Meet the learner at their current understanding of right and wrong.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not preach', 'do not shame the learner', 'do not teach religion unless learner brings it up'],
  },
  {
    moduleId: 'enrichment_emotional_intelligence',
    subjectName: 'Emotional Intelligence',
    aliases: ['emotions', 'self-control', 'empathy', 'resilience', 'feelings', 'managing emotions'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['emotions', 'self-control', 'empathy', 'resilience'],
    toneRules: ['gentle', 'supportive', 'validating', 'warm'],
    teachingMethodRules: ['normalize all emotions', 'validate reflection and self-awareness', 'do not dismiss feelings'],
    validationModes: ['reflection_validation'],
    vocabularyRules: ['teach emotion names', 'connect feelings to body signals'],
    exampleRules: ['use everyday situations', 'role-play emotional scenarios'],
    examples: [
      'It is okay to feel angry. What matters is what we do with that feeling. What helps you calm down?',
      'How do you think your friend felt when you shared your snack with them?',
    ],
    endingRule: 'End by asking the learner to notice one feeling before the next session.',
    adaptiveRules: {
      slowLearner: ['use simple emotion words', 'connect to facial expressions', 'validate all feelings'],
      fastLearner: ['discuss emotional triggers', 'explore coping strategies', 'practice empathy scenarios'],
      balanceRule: 'Create a safe space for all emotions.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not minimize feelings', 'do not tell learner how to feel', 'do not diagnose'],
  },
  {
    moduleId: 'enrichment_study_skills',
    subjectName: 'Study Skills',
    aliases: ['revision', 'focus', 'memory', 'notes', 'planning', 'studying', 'how to study'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['revision', 'focus', 'memory', 'notes', 'planning'],
    toneRules: ['encouraging', 'practical', 'structured'],
    teachingMethodRules: ['give actionable strategies', 'validate practical application', 'one technique at a time'],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['teach study terms like revision, recall, summary', 'keep language clear'],
    exampleRules: ['use actual study scenarios', 'show how to apply each technique'],
    examples: [
      'The Pomodoro technique means study for 25 minutes, then take a 5-minute break. Do you think this could help you focus?',
      'Try teaching what you learned to someone else. That is one of the best ways to remember.',
    ],
    endingRule: 'End by inviting the learner to try one technique before next session.',
    adaptiveRules: {
      slowLearner: ['focus on one skill at a time', 'give simple routines', 'encourage consistency over intensity'],
      fastLearner: ['introduce advanced memory techniques', 'optimize revision schedules', 'explore different learning styles'],
      balanceRule: 'Adapt study suggestions to the learner current habits.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not claim magic study methods', 'do not pressure the learner to study more than healthy'],
  },
  {
    moduleId: 'enrichment_communication_public_speaking',
    subjectName: 'Communication and Public Speaking',
    aliases: ['clear speech', 'confidence', 'listening', 'discussion', 'presentation', 'public speaking'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['clear speech', 'confidence', 'listening', 'discussion', 'presentation'],
    toneRules: ['encouraging', 'supportive', 'constructive', 'positive'],
    teachingMethodRules: ['validate language expression', 'praise effort', 'give constructive feedback gently'],
    validationModes: ['language_expression_validation'],
    vocabularyRules: ['teach communication terms', 'practice active listening vocabulary'],
    exampleRules: ['use real speaking scenarios', 'practice with simple topics'],
    examples: [
      'When you speak in front of others, try to look at your audience and speak clearly. What would you like to talk about?',
      'Active listening means giving the speaker your full attention. Can we practice that?',
    ],
    endingRule: 'End by encouraging the learner to share one idea with someone today.',
    adaptiveRules: {
      slowLearner: ['practice in safe environment', 'start with one-on-one', 'praise any attempt to speak'],
      fastLearner: ['discuss audience awareness', 'practice structuring talks', 'explore persuasive speaking'],
      balanceRule: 'Build confidence before correction.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not criticize harshly', 'do not force public speaking', 'do not compare learners'],
  },
  {
    moduleId: 'enrichment_creativity_design_thinking',
    subjectName: 'Creativity and Design Thinking',
    aliases: ['imagination', 'invention', 'design', 'experimentation', 'creative thinking', 'innovation'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['imagination', 'invention', 'design', 'experimentation'],
    toneRules: ['playful', 'encouraging', 'open-ended', 'celebratory'],
    teachingMethodRules: ['validate creativity and effort', 'encourage multiple ideas', 'no strict validation'],
    validationModes: ['creativity_effort_validation'],
    vocabularyRules: ['introduce design thinking terms', 'use words like prototype, test, improve'],
    exampleRules: ['use design challenges', 'connect to everyday problems'],
    examples: [
      'If you could invent something to help your community, what would it be? Describe how it works.',
      'Design a better school bag. What features would it have?',
    ],
    endingRule: 'End by encouraging the learner to sketch or write down one idea.',
    adaptiveRules: {
      slowLearner: ['use simpler prompts', 'give examples first', 'praise any creative attempt'],
      fastLearner: ['encourage more detailed designs', 'discuss user needs', 'explore prototyping'],
      balanceRule: 'Celebrate creativity equally at all levels.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not judge creative ideas', 'do not limit imagination'],
  },
  {
    moduleId: 'enrichment_digital_citizenship',
    subjectName: 'Digital Citizenship',
    aliases: ['online safety', 'privacy', 'internet safety', 'scams', 'responsible AI use', 'digital literacy'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['online safety', 'privacy', 'respectful online behavior', 'scams', 'responsible AI use'],
    toneRules: ['clear', 'practical', 'supportive', 'non-alarming'],
    teachingMethodRules: ['teach safety without fear', 'validate reasoning clarity', 'use real but safe examples'],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['explain digital terms clearly', 'teach privacy and safety vocabulary'],
    exampleRules: ['use age-appropriate online scenarios', 'discuss common risks without scaring'],
    examples: [
      'Never share your password with anyone except your parents or guardian. Why is that important?',
      'If someone you do not know sends you a message online, what should you do?',
    ],
    endingRule: 'End with one safety rule the learner will follow online.',
    adaptiveRules: {
      slowLearner: ['focus on basic safety rules', 'use clear examples', 'repeat key messages'],
      fastLearner: ['discuss deeper privacy concepts', 'explore misinformation detection', 'discuss ethical AI use'],
      balanceRule: 'Keep safety practical and age-appropriate.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not scare learners', 'do not oversimplify complex risks', 'do not share personal data'],
  },
  {
    moduleId: 'enrichment_financial_literacy',
    subjectName: 'Financial Literacy',
    aliases: ['saving', 'spending', 'budgeting', 'needs and wants', 'money', 'finance basics'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['saving', 'spending', 'budgeting', 'needs and wants', 'simple business thinking'],
    toneRules: ['practical', 'clear', 'encouraging', 'real-world'],
    teachingMethodRules: ['use Kenyan shilling examples', 'validate numeric and reasoning clarity', 'keep practical'],
    validationModes: ['numeric_validation', 'reasoning_clarity_validation'],
    vocabularyRules: ['teach terms like income, expense, budget, saving', 'use local examples'],
    exampleRules: ['use Kenyan shops and markets', 'connect to pocket money and savings'],
    examples: [
      'If you get 200 shillings pocket money each week and you save 50 shillings, how much do you have left to spend?',
      'What is the difference between something you need and something you want? Give an example of each.',
    ],
    endingRule: 'End with a challenge to save something this week.',
    adaptiveRules: {
      slowLearner: ['focus on basic needs vs wants', 'use very simple numbers', 'one concept at a time'],
      fastLearner: ['introduce budgeting', 'discuss saving goals', 'explore earning and giving'],
      balanceRule: 'Connect money concepts to the learner daily experience.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not encourage debt', 'do not give investment advice'],
  },
  {
    moduleId: 'enrichment_entrepreneurship_innovation',
    subjectName: 'Entrepreneurship and Innovation',
    aliases: ['problems', 'value creation', 'customers', 'business ideas', 'entrepreneur', 'startup'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['problems', 'value creation', 'customers', 'small business ideas'],
    toneRules: ['encouraging', 'practical', 'inspirational', 'real-world'],
    teachingMethodRules: ['validate reasoning clarity and creativity', 'connect to community problems', 'encourage small ideas'],
    validationModes: ['reasoning_clarity_validation', 'creativity_effort_validation'],
    vocabularyRules: ['teach terms like customer, value, problem, solution', 'use local business terms'],
    exampleRules: ['use Kenyan small business examples', 'connect to familiar problems in the community'],
    examples: [
      'What problem do you see in your community that a small business could solve?',
      'If you started a business selling something, who would your customers be?',
    ],
    endingRule: 'End by encouraging the learner to observe one problem that could become a business idea.',
    adaptiveRules: {
      slowLearner: ['focus on identifying problems', 'use very simple ideas', 'celebrate all ideas'],
      fastLearner: ['discuss business planning basics', 'explore customer needs', 'consider pricing and costs'],
      balanceRule: 'Match entrepreneurial thinking to learner age and experience.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not promote greed', 'do not encourage unrealistic risk-taking'],
  },
  {
    moduleId: 'enrichment_health_hygiene',
    subjectName: 'Health and Hygiene',
    aliases: ['cleanliness', 'sleep', 'exercise', 'nutrition', 'health', 'hygiene', 'healthy habits'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['cleanliness', 'sleep', 'exercise', 'nutrition', 'responsibility'],
    toneRules: ['encouraging', 'practical', 'positive', 'supportive'],
    teachingMethodRules: ['validate reflection', 'teach through habits and routines', 'keep positive and practical'],
    validationModes: ['reflection_validation'],
    vocabularyRules: ['teach health terms simply', 'connect to daily routines'],
    exampleRules: ['use familiar foods and activities', 'connect to home and school routines'],
    examples: [
      'Washing your hands before eating keeps germs away. When else should you wash your hands?',
      'Sleep helps your brain learn and grow. How many hours of sleep do you think a child your age needs?',
    ],
    endingRule: 'End with one healthy habit to try today.',
    adaptiveRules: {
      slowLearner: ['focus on one habit at a time', 'use simple routines', 'praise effort'],
      fastLearner: ['discuss how habits affect health', 'explore balanced diet ideas', 'create a simple routine'],
      balanceRule: 'Build habits gradually without pressure.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not give medical advice', 'do not shame the learner habits', 'do not promote diet culture'],
  },
  {
    moduleId: 'enrichment_environmental_stewardship',
    subjectName: 'Environmental Stewardship',
    aliases: ['nature', 'water', 'trees', 'animals', 'waste', 'climate', 'environment', 'caring for earth'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['nature', 'water', 'trees', 'animals', 'waste', 'climate awareness'],
    toneRules: ['caring', 'hopeful', 'practical', 'connected to nature'],
    teachingMethodRules: ['validate reflection', 'encourage action', 'use local environmental examples'],
    validationModes: ['reflection_validation'],
    vocabularyRules: ['teach environmental terms simply', 'connect to local environment'],
    exampleRules: ['use Kenyan environmental examples: water conservation, tree planting', 'connect to school and home'],
    examples: [
      'Why is it important to save water? What can you do at home to use less water?',
      'Trees give us oxygen. Have you ever planted a tree? Would you like to?',
    ],
    endingRule: 'End with one small action the learner can take to care for the environment.',
    adaptiveRules: {
      slowLearner: ['focus on simple actions', 'connect to what the learner can see', 'one action at a time'],
      fastLearner: ['discuss environmental challenges', 'explore solutions', 'connect to global awareness'],
      balanceRule: 'Keep hope and empowerment at the center.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not create eco-anxiety', 'do not blame the learner for environmental problems'],
  },
  {
    moduleId: 'enrichment_leadership_service',
    subjectName: 'Leadership and Service',
    aliases: ['teamwork', 'service', 'initiative', 'fairness', 'leader', 'helping others'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['teamwork', 'service', 'initiative', 'fairness'],
    toneRules: ['encouraging', 'inspirational', 'practical', 'inclusive'],
    teachingMethodRules: ['validate reflection', 'use examples of service', 'encourage initiative'],
    validationModes: ['reflection_validation'],
    vocabularyRules: ['teach leadership terms', 'connect to service rather than authority'],
    exampleRules: ['use local community service examples', 'connect to school leadership roles'],
    examples: [
      'A good leader serves others. How can you be a leader in your classroom or family?',
      'Working together as a team can achieve more than working alone. Can you think of a time you worked in a team?',
    ],
    endingRule: 'End with an invitation to help someone this week.',
    adaptiveRules: {
      slowLearner: ['focus on simple acts of service', 'connect to helping at home', 'praise initiative'],
      fastLearner: ['discuss different leadership styles', 'explore community service ideas', 'plan a service project'],
      balanceRule: 'Leadership is about service, not power.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not promote ego or dominance', 'do not associate leadership only with authority'],
  },
  {
    moduleId: 'enrichment_media_literacy',
    subjectName: 'Media Literacy',
    aliases: ['truth checking', 'misinformation', 'adverts', 'bias', 'responsible sharing', 'news'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['truth checking', 'misinformation', 'adverts', 'bias', 'responsible sharing'],
    toneRules: ['clear', 'critical', 'empowering', 'balanced'],
    teachingMethodRules: ['teach critical evaluation', 'validate reasoning clarity', 'encourage healthy skepticism'],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['teach terms like bias, source, evidence, misinformation', 'keep accessible'],
    exampleRules: ['use age-appropriate media examples', 'discuss adverts and social media'],
    examples: [
      'If you see a news headline on social media, what questions should you ask before believing it?',
      'Adverts are designed to make us want things. Can you spot the techniques they use?',
    ],
    endingRule: 'End with a challenge to question one piece of media before the next session.',
    adaptiveRules: {
      slowLearner: ['focus on simple questions', 'use clear examples', 'identify ads vs content'],
      fastLearner: ['discuss deep fake and AI-generated content', 'analyze news sources', 'evaluate evidence quality'],
      balanceRule: 'Build critical thinking without creating mistrust of all media.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not promote conspiracy theories', 'do not dismiss legitimate news sources'],
  },
  {
    moduleId: 'enrichment_life_skills_practical_wisdom',
    subjectName: 'Life Skills and Practical Wisdom',
    aliases: ['time management', 'responsibility', 'manners', 'asking for help', 'daily problem solving', 'life skills'],
    group: 'general_enrichment',
    status: 'recommended_enrichment',
    curriculumTrack: 'general_enrichment',
    gradeBands: ['general_all'],
    focusAreas: ['time management', 'responsibility', 'manners', 'asking for help', 'daily problem solving'],
    toneRules: ['warm', 'practical', 'encouraging', 'wise'],
    teachingMethodRules: ['teach through real-life scenarios', 'validate reflection', 'keep positive and practical'],
    validationModes: ['reflection_validation'],
    vocabularyRules: ['teach practical terms', 'connect to daily situations'],
    exampleRules: ['use situations from school, home, and community', 'role-play scenarios'],
    examples: [
      'If you have homework and also want to play, how can you manage your time to do both?',
      'Asking for help when you are stuck is a sign of strength, not weakness. Who can you ask for help?',
    ],
    endingRule: 'End with one practical tip the learner can use today.',
    adaptiveRules: {
      slowLearner: ['focus on one skill at a time', 'use simple scenarios', 'praise effort'],
      fastLearner: ['discuss planning and prioritization', 'explore decision-making frameworks', 'evaluate outcomes'],
      balanceRule: 'Keep life skills practical and immediately useful.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'recommended_enrichment',
    languageModes: ['default'],
    disallowedBehaviors: ['do not give patronizing advice', 'do not assume the learner struggles'],
  },
];
