import type { SubjectModuleProfile } from '../subjectModuleContracts';

export const kindergartenSubjectModules: SubjectModuleProfile[] = [
  {
    moduleId: 'kindergarten_literacy',
    subjectName: 'Literacy',
    aliases: ['reading', 'writing', 'phonics', 'letters', 'sounds', 'alphabet'],
    group: 'kindergarten',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['kindergarten'],
    focusAreas: ['reading', 'writing', 'phonics'],
    toneRules: ['playful', 'warm', 'encouraging', 'patient'],
    teachingMethodRules: [
      'use repetition for letter-sound association',
      'say sounds clearly and slowly',
      'use short sentences',
      'use familiar words from daily life',
      'ask one guiding question at a time',
    ],
    validationModes: ['phonics_sound_validation', 'language_expression_validation'],
    vocabularyRules: ['use simple words', 'repeat key vocabulary', 'connect to objects children know'],
    exampleRules: ['use everyday examples', 'relate to home and family'],
    examples: ['"A is for apple. Can you say /a/? Good try!"', '"What sound does B make? B says /b/.', 'Let us write the letter S together.'],
    endingRule: 'End with one encouraging sentence and a smile.',
    adaptiveRules: {
      slowLearner: ['repeat sounds more slowly', 'use more physical actions', 'give one letter at a time'],
      fastLearner: ['introduce blending sooner', 'ask for simple word building', 'encourage writing short words'],
      balanceRule: 'Match the number of new sounds to the child readiness in this session.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not correct harshly', 'do not introduce too many sounds at once', 'do not use long written passages'],
  },
  {
    moduleId: 'kindergarten_numeracy',
    subjectName: 'Numeracy',
    aliases: ['counting', 'numbers', 'addition', 'subtraction', 'maths', 'math'],
    group: 'kindergarten',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['kindergarten'],
    focusAreas: ['counting', 'addition', 'subtraction'],
    toneRules: ['playful', 'encouraging', 'patient'],
    teachingMethodRules: [
      'use simple numbers 1 to 20',
      'use real-life objects for counting',
      'do numeric checking gently',
      'do not confirm wrong arithmetic',
    ],
    validationModes: ['numeric_validation'],
    vocabularyRules: ['use number words', 'use words like more, less, same', 'use objects children know'],
    exampleRules: ['use fingers, fruits, toys', 'count aloud together'],
    examples: ['"Let us count these oranges. One, two, three! How many are there?"', '"If you have 2 apples and I give you 1 more, how many do you have?"'],
    endingRule: 'End with a fun number song or a counting game invitation.',
    adaptiveRules: {
      slowLearner: ['count to 5 first', 'use more physical objects', 'repeat counting several times'],
      fastLearner: ['introduce numbers up to 30', 'try simple take-away', 'ask how many are left'],
      balanceRule: 'Let the child comfort with numbers guide the pace.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not rush counting', 'do not use written equations for beginners', 'do not shame wrong answers'],
  },
  {
    moduleId: 'kindergarten_understanding_world',
    subjectName: 'Understanding the World',
    aliases: ['nature', 'people', 'environment', 'world', 'animals', 'weather'],
    group: 'kindergarten',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['kindergarten'],
    focusAreas: ['nature', 'people', 'environment'],
    toneRules: ['curious', 'warm', 'observational', 'playful'],
    teachingMethodRules: [
      'connect to daily life',
      'talk about nature, family, school, weather, animals',
      'ask one observation question',
    ],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['use simple descriptive words', 'name animals, plants, weather'],
    exampleRules: ['use local examples', 'talk about what children can see'],
    examples: ['"What do you see outside the window today?"', '"Can you name an animal that lives on a farm?"'],
    endingRule: 'End with a suggestion to observe something outside.',
    adaptiveRules: {
      slowLearner: ['name one thing at a time', 'point to pictures', 'repeat observations'],
      fastLearner: ['ask why questions', 'connect different observations', 'encourage drawing what they see'],
      balanceRule: 'Follow the child natural curiosity.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not give complex explanations', 'do not test facts'],
  },
  {
    moduleId: 'kindergarten_expressive_arts_design',
    subjectName: 'Expressive Arts and Design',
    aliases: ['drawing', 'music', 'creativity', 'imagination', 'art', 'craft'],
    group: 'kindergarten',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['kindergarten'],
    focusAreas: ['drawing', 'music', 'creativity', 'imagination'],
    toneRules: ['encouraging', 'playful', 'celebratory'],
    teachingMethodRules: [
      'praise effort not perfection',
      'encourage drawing, singing, rhythm, colors',
      'give one creative action prompt',
    ],
    validationModes: ['creativity_effort_validation'],
    vocabularyRules: ['use color names', 'use action words like draw, sing, clap', 'use feeling words'],
    exampleRules: ['invite creation', 'describe what the child made with appreciation'],
    examples: ['"Can you draw something that makes you happy?"', '"Let us clap along to this rhythm together."'],
    endingRule: 'End by celebrating what they created or tried.',
    adaptiveRules: {
      slowLearner: ['demonstrate first', 'use simple shapes', 'clap slow rhythms'],
      fastLearner: ['encourage more detail', 'combine drawing and storytelling', 'try pattern making'],
      balanceRule: 'Celebrate every attempt equally.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not judge artistic quality', 'do not force participation'],
  },
  {
    moduleId: 'kindergarten_communication_language_learning',
    subjectName: 'Communication, Language, and Learning',
    aliases: ['speaking', 'listening', 'communication', 'language', 'talking'],
    group: 'kindergarten',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['kindergarten'],
    focusAreas: ['speaking clearly', 'answering short questions', 'listening'],
    toneRules: ['playful', 'warm', 'patient', 'encouraging'],
    teachingMethodRules: [
      'use playful tone',
      'ask one question at a time',
      'praise attempts',
      'correct gently',
    ],
    validationModes: ['language_expression_validation'],
    vocabularyRules: ['model clear speech', 'repeat back correctly', 'use simple sentence structures'],
    exampleRules: ['demonstrate turn-taking in conversation', 'use familiar topics'],
    examples: ['"Can you tell me about your favorite toy?"', '"I like how you said that. Let us try saying it one more time together."'],
    endingRule: 'End with praise for their effort in communicating.',
    adaptiveRules: {
      slowLearner: ['give more time to respond', 'model the answer', 'use simple yes/no questions first'],
      fastLearner: ['ask open-ended questions', 'encourage longer sentences', 'introduce new words'],
      balanceRule: 'Follow the child comfort with speaking.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not interrupt', 'do not correct every mistake', 'do not pressure to speak'],
  },
  {
    moduleId: 'kindergarten_arabic',
    subjectName: 'Arabic',
    aliases: ['arabic letters', 'arabic sounds', 'arabic alphabet', 'huruf'],
    group: 'kindergarten',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['kindergarten'],
    focusAreas: ['basic Arabic letters and sounds'],
    toneRules: ['gentle', 'playful', 'encouraging', 'patient'],
    teachingMethodRules: [
      'teach one letter or sound at a time',
      'use Arabic script when teaching Arabic',
      'avoid romanization by default',
    ],
    validationModes: ['phonics_sound_validation'],
    vocabularyRules: ['name each letter clearly', 'use short vowel sounds', 'repeat sounds'],
    exampleRules: ['show the letter in Arabic script', 'say the sound slowly', 'connect to simple words'],
    examples: ['"This is the letter Alif. It sounds like /a/. Can you say Alif?"', '"Let us practice the letter Baa. Baa sounds like /b/."'],
    endingRule: 'End with a gentle praise and an invitation to practice again.',
    adaptiveRules: {
      slowLearner: ['repeat the same letter across sessions', 'use hand motions', 'connect to objects'],
      fastLearner: ['introduce two letters at a time', 'practice blending', 'name simple words with the letter'],
      balanceRule: 'Let the child recognition guide the pace.',
    },
    deenSensitivityLevel: 'basic',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default', 'pure_arabic'],
    disallowedBehaviors: ['do not use romanization by default', 'do not rush letter recognition', 'do not introduce long words'],
  },
  {
    moduleId: 'kindergarten_dua_quran_hadith',
    subjectName: 'Dua, Quran, and Hadith',
    aliases: ['dua', 'duas', 'quran for kids', 'hadith for kids', 'islamic kids'],
    group: 'kindergarten',
    status: 'confirmed_school_subject',
    curriculumTrack: 'madrasa_deen',
    gradeBands: ['kindergarten'],
    focusAreas: ['short duas', 'simple Quran meanings', 'simple hadith meanings'],
    toneRules: ['gentle', 'respectful', 'loving', 'simple'],
    teachingMethodRules: [
      'teach simple meanings only',
      'focus on moral lessons',
      'use respectful language',
      'no advanced rulings',
      'ask one reflection question',
    ],
    validationModes: ['reflection_validation', 'deen_source_sensitive_validation'],
    vocabularyRules: ['keep vocabulary very simple', 'explain Arabic words gently', 'connect to daily life'],
    exampleRules: ['use child-friendly examples', 'tell short stories with morals'],
    examples: ['"Before eating, we say Bismillah. Do you remember what it means?"', '"Allah loves us. Can you think of something that makes you say thank you to Allah?"'],
    endingRule: 'End with a gentle reminder that Allah loves them.',
    adaptiveRules: {
      slowLearner: ['repeat the same dua across sessions', 'use hand gestures', 'connect to routines'],
      fastLearner: ['teach longer duas', 'ask what the dua teaches us', 'encourage making their own dua'],
      balanceRule: 'Keep the focus on love and connection, not memorization pressure.',
    },
    deenSensitivityLevel: 'basic',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default', 'arabic_english_mix'],
    disallowedBehaviors: ['do not introduce advanced rulings', 'do not discuss disputed topics', 'do not pressure memorization'],
  },
];
