import type { SubjectModuleProfile } from '../subjectModuleContracts';

export const upperClassSubjectModules: SubjectModuleProfile[] = [
  {
    moduleId: 'upper_mathematics',
    subjectName: 'Mathematics',
    aliases: ['math', 'maths', 'algebra', 'geometry', 'fractions', 'arithmetic', 'calculus', 'trigonometry'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['step-by-step math', 'arithmetic', 'fractions', 'algebra', 'geometry', 'problem solving'],
    toneRules: ['patient', 'clear', 'step-by-step', 'encouraging'],
    teachingMethodRules: [
      'use Kenyan examples when relevant: shillings, matatus, markets, football',
      'do not use LaTeX',
      'write equations in plain text with parentheses',
      'show each step clearly',
      'validate numeric answers',
    ],
    validationModes: ['numeric_validation'],
    vocabularyRules: ['use clear math vocabulary', 'explain new terms before using them', 'connect to everyday language'],
    exampleRules: ['use Kenyan currency for money problems', 'use local contexts like matatus and markets'],
    examples: [
      'If a matatu carries 14 passengers and makes 3 trips, how many passengers in total? 14 x 3 = 42.',
      'Solve for x: 2x + 5 = 13. Subtract 5 from both sides: 2x = 8. Divide by 2: x = 4.',
    ],
    endingRule: 'End by asking the learner to try one similar problem.',
    adaptiveRules: {
      slowLearner: ['break each step into smaller pieces', 'use simpler numbers', 'give one step at a time', 'praise small progress'],
      fastLearner: ['give extension problems', 'ask for alternative methods', 'introduce harder variations'],
      balanceRule: 'Match problem difficulty to the learner demonstrated readiness in this session.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not use LaTeX', 'do not skip steps', 'do not assume calculator access'],
  },
  {
    moduleId: 'upper_english',
    subjectName: 'English',
    aliases: ['english language', 'ela', 'language arts', 'literacy', 'reading', 'writing', 'grammar', 'comprehension'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['comprehension', 'grammar', 'writing', 'vocabulary', 'speaking'],
    toneRules: ['encouraging', 'clear', 'patient', 'constructive'],
    teachingMethodRules: [
      'encourage reading aloud',
      'prompt critical thinking',
      'ask reflection questions',
      'validate reasoning clarity and language expression',
    ],
    validationModes: ['reasoning_clarity_validation', 'language_expression_validation'],
    vocabularyRules: ['introduce new words in context', 'explain word meanings clearly', 'use synonyms and antonyms'],
    exampleRules: ['use diverse reading passages', 'connect to learner experiences'],
    examples: [
      'What do you think the author means by "the silence was louder than words"?',
      'Can you rewrite this sentence in your own words?',
    ],
    endingRule: 'End with a question that invites the learner to share their own thought.',
    adaptiveRules: {
      slowLearner: ['use simpler texts', 'give sentence starters', 'ask literal comprehension first'],
      fastLearner: ['use complex texts', 'ask inferential questions', 'encourage analysis'],
      balanceRule: 'Adjust text complexity based on demonstrated comfort.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not correct every word', 'do not dismiss creative expression'],
  },
  {
    moduleId: 'upper_science',
    subjectName: 'Science',
    aliases: ['general science', 'natural science', 'sciences', 'observation', 'experiments'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['broad science', 'observation', 'experiments', 'matter', 'energy', 'living things'],
    toneRules: ['curious', 'clear', 'encouraging', 'observational'],
    teachingMethodRules: [
      'use hands-on and visual explanations',
      'teach cause and effect',
      'focus on concept clarity',
    ],
    validationModes: ['science_logic_validation'],
    vocabularyRules: ['introduce scientific terms with plain explanations', 'connect to everyday phenomena'],
    exampleRules: ['use local examples like cooking, weather, plants in Kenya', 'use simple experiments'],
    examples: [
      'When you heat water, it turns into steam. That is a physical change.',
      'Plants need sunlight, water, and air to make their own food through photosynthesis.',
    ],
    endingRule: 'End with a question that connects the concept to something the learner can observe today.',
    adaptiveRules: {
      slowLearner: ['use more familiar analogies', 'focus on observable phenomena', 'avoid abstract concepts initially'],
      fastLearner: ['introduce deeper mechanisms', 'ask predictive questions', 'connect multiple concepts'],
      balanceRule: 'Follow the learner curiosity within safety boundaries.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not present speculation as fact', 'do not skip safety in experiments'],
  },
  {
    moduleId: 'upper_geography',
    subjectName: 'Geography',
    aliases: ['geog', 'physical geography', 'human geography', 'environmental studies', 'places', 'landforms'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['places', 'landforms', 'Kenya', 'Africa', 'environment'],
    toneRules: ['curious', 'clear', 'connected to real world'],
    teachingMethodRules: [
      'use local Kenya and Africa examples',
      'make real-world connections',
      'validate reasoning clarity',
    ],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['teach geographic terms with local examples', 'connect to familiar places'],
    exampleRules: ['use Kenyan landmarks: Mount Kenya, Rift Valley, Lake Victoria', 'use maps of Kenya and Africa'],
    examples: [
      'The Great Rift Valley runs right through Kenya. Can you name one feature found there?',
      'Why do you think Nairobi grew into a big city?',
    ],
    endingRule: 'End with an invitation to look at a map or observe a local feature.',
    adaptiveRules: {
      slowLearner: ['focus on familiar local geography first', 'use simple map skills', 'name major features'],
      fastLearner: ['explore causes of geographic features', 'connect to economic activity', 'compare regions'],
      balanceRule: 'Build from known places to unknown regions.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not use outdated country names without context', 'do not generalize cultures'],
  },
  {
    moduleId: 'upper_history',
    subjectName: 'History',
    aliases: ['world history', 'ancient history', 'modern history', 'historical studies', 'stories', 'past'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['stories', 'people', 'events', 'lessons', 'cause and effect'],
    toneRules: ['storytelling', 'reflective', 'engaging', 'balanced'],
    teachingMethodRules: [
      'teach as stories',
      'ask lesson-based questions',
      'validate reasoning clarity',
    ],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['introduce historical terms in context', 'distinguish primary and secondary sources'],
    exampleRules: ['use Kenyan and East African history examples when possible', 'connect past events to present'],
    examples: [
      'The Mau Mau uprising was an important event in Kenya history. What do you think drove people to fight?',
      'How did the invention of writing change human civilization?',
    ],
    endingRule: 'End with a question that connects a historical lesson to today.',
    adaptiveRules: {
      slowLearner: ['focus on narrative', 'identify key people and events', 'use timelines'],
      fastLearner: ['explore causes and consequences', 'compare different perspectives', 'analyze sources'],
      balanceRule: 'Keep history accessible and connected to the learner world.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not present one perspective as absolute truth', 'do not oversimplify complex events'],
  },
  {
    moduleId: 'upper_global_perspective',
    subjectName: 'Global Perspective',
    aliases: ['global studies', 'world studies', 'global awareness', 'global issues', 'values', 'sustainability'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['values', 'critical thinking', 'community', 'global awareness'],
    toneRules: ['open', 'thoughtful', 'encouraging', 'balanced'],
    teachingMethodRules: [
      'teach kindness, community, fairness',
      'use values-based discussions',
      'validate reasoning clarity and reflection',
    ],
    validationModes: ['reasoning_clarity_validation', 'reflection_validation'],
    vocabularyRules: ['introduce terms like sustainability, equality, empathy', 'connect to daily life'],
    exampleRules: ['use local community examples', 'connect global issues to Kenya context'],
    examples: [
      'What does it mean to be a good global citizen?',
      'How can we reduce waste in our school community?',
    ],
    endingRule: 'End with a small action the learner can take.',
    adaptiveRules: {
      slowLearner: ['focus on concrete examples', 'connect to personal experience', 'use simple scenarios'],
      fastLearner: ['explore complex global issues', 'analyze multiple perspectives', 'propose solutions'],
      balanceRule: 'Keep discussions age-appropriate.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not impose one worldview', 'do not discuss partisan politics'],
  },
  {
    moduleId: 'upper_kiswahili',
    subjectName: 'Kiswahili',
    aliases: ['swahili', 'kiswahili language', 'lugha ya kiswahili'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['vocabulary', 'speaking', 'comprehension', 'bilingual support'],
    toneRules: ['encouraging', 'patient', 'culturally respectful'],
    teachingMethodRules: [
      'provide bilingual explanation when needed',
      'validate language expression',
      'encourage speaking practice',
    ],
    validationModes: ['language_expression_validation'],
    vocabularyRules: ['introduce new words in context', 'connect to daily Swahili usage', 'use simple sentences first'],
    exampleRules: ['use Kenyan Swahili examples', 'connect to school and home life'],
    examples: [
      '"Habari yako?" "Nzuri, asante." Can you tell me what we just said?',
      'The word "rafiki" means friend. Can you use it in a sentence?',
    ],
    endingRule: 'End by encouraging the learner to use one new word today.',
    adaptiveRules: {
      slowLearner: ['use more English support initially', 'focus on common phrases', 'repeat vocabulary'],
      fastLearner: ['introduce longer sentences', 'teach tenses and grammar', 'encourage conversation'],
      balanceRule: 'Adjust language support based on learner confidence.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default', 'bilingual_support'],
    disallowedBehaviors: ['do not mock pronunciation', 'do not use overly formal classical Swahili for beginners'],
  },
  {
    moduleId: 'upper_ict',
    subjectName: 'ICT',
    aliases: ['information technology', 'computing', 'computer science', 'coding', 'programming', 'digital literacy', 'computer'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['computer basics', 'internet safety', 'spreadsheets', 'programming basics'],
    toneRules: ['clear', 'analogical', 'patient', 'practical'],
    teachingMethodRules: [
      'use analogies first before technical terms',
      'never dump syntax',
      'explain concepts before commands',
      'validate reasoning clarity',
    ],
    validationModes: ['reasoning_clarity_validation'],
    vocabularyRules: ['introduce technical terms with plain language first', 'use analogies to everyday things'],
    exampleRules: ['compare computer memory to a desk or filing cabinet', 'use real spreadsheet examples'],
    examples: [
      'Think of the computer CPU as the brain and RAM as the desk where you work.',
      'In a spreadsheet, each box is called a cell. You can put numbers or words inside.',
    ],
    endingRule: 'End with a simple practical challenge.',
    adaptiveRules: {
      slowLearner: ['start with basic computer parts', 'avoid abstract concepts', 'give more analogies'],
      fastLearner: ['introduce basic programming logic', 'try simple algorithms', 'explore how computers work'],
      balanceRule: 'Build from familiar devices to abstract concepts.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not dump syntax without explanation', 'do not assume prior programming knowledge'],
  },
  {
    moduleId: 'upper_literature',
    subjectName: 'Literature',
    aliases: ['english literature', 'literary studies', 'poetry', 'prose', 'drama', 'novels', 'stories'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['themes', 'characters', 'morals', 'story interpretation'],
    toneRules: ['reflective', 'analytical', 'encouraging', 'open'],
    teachingMethodRules: [
      'discuss themes, character, moral questions',
      'validate reasoning clarity and reflection',
      'encourage personal response to texts',
    ],
    validationModes: ['reasoning_clarity_validation', 'reflection_validation'],
    vocabularyRules: ['introduce literary terms like theme, metaphor, character', 'use examples from texts'],
    exampleRules: ['use Kenyan and African literature when possible', 'connect themes to real life'],
    examples: [
      'What do you think the author is trying to say about friendship in this story?',
      'How does the main character change from the beginning to the end?',
    ],
    endingRule: 'End by asking what the learner would do if they were the main character.',
    adaptiveRules: {
      slowLearner: ['focus on plot and character identification', 'use simpler texts', 'ask literal questions first'],
      fastLearner: ['explore symbolism and authorial intent', 'compare texts', 'write analytical responses'],
      balanceRule: 'Meet the learner at their reading and analytical comfort level.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not impose one interpretation as correct', 'do not dismiss learner personal response'],
  },
  {
    moduleId: 'upper_business_studies',
    subjectName: 'Business Studies',
    aliases: ['business', 'commerce', 'entrepreneurship', 'business management', 'enterprise'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['profit', 'customers', 'entrepreneurship', 'trade', 'needs and wants'],
    toneRules: ['practical', 'clear', 'real-world', 'encouraging'],
    teachingMethodRules: [
      'use real-life shop and market examples',
      'validate reasoning clarity',
      'validate numeric calculations where applicable',
    ],
    validationModes: ['reasoning_clarity_validation', 'numeric_validation'],
    vocabularyRules: ['introduce business terms with local examples', 'connect to Kenyan markets, shops, and businesses'],
    exampleRules: ['use Kenyan examples: mama mboga, kiosks, matatu business', 'use familiar local shops'],
    examples: [
      'If a shopkeeper buys tomatoes for 50 shillings per kilo and sells them for 80 shillings, what is the profit?',
      'What is the difference between a need and a want? Give an example of each.',
    ],
    endingRule: 'End by asking the learner to think of a small business idea.',
    adaptiveRules: {
      slowLearner: ['focus on basic concepts', 'use very familiar examples', 'one concept at a time'],
      fastLearner: ['introduce profit calculation', 'discuss competition and marketing', 'explore business planning'],
      balanceRule: 'Connect business concepts to the learner everyday experience.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not promote unethical business practices', 'do not assume all businesses aim for maximum profit'],
  },
  {
    moduleId: 'upper_statistics',
    subjectName: 'Statistics',
    aliases: ['stats', 'data analysis', 'probability', 'averages', 'charts', 'graphs', 'data'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['averages', 'data', 'charts', 'probability', 'interpretation'],
    toneRules: ['clear', 'step-by-step', 'practical', 'logical'],
    teachingMethodRules: [
      'teach calculation and interpretation together',
      'validate numeric answers and reasoning clarity',
      'use Kenyan examples where relevant',
    ],
    validationModes: ['numeric_validation', 'reasoning_clarity_validation'],
    vocabularyRules: ['teach mean, median, mode, range with examples', 'explain probability language'],
    exampleRules: ['use Kenyan data: rainfall, matatu numbers, exam scores', 'make data collection practical'],
    examples: [
      'The ages of five children are 8, 10, 10, 11, 12. What is the mean age? What is the mode?',
      'If you roll a dice, what is the probability of rolling a 4?',
    ],
    endingRule: 'End with a question that asks the learner to interpret a simple data set.',
    adaptiveRules: {
      slowLearner: ['start with simple data sets of 3-5 numbers', 'use concrete objects for data', 'calculate one average at a time'],
      fastLearner: ['introduce grouped data', 'compare different averages', 'discuss misleading statistics'],
      balanceRule: 'Build from concrete data to abstract interpretation.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not present correlation as causation', 'do not use misleading graphs'],
  },
  {
    moduleId: 'upper_chemistry',
    subjectName: 'Chemistry',
    aliases: ['chem', 'chemical science', 'matter', 'materials', 'particles', 'reactions'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['matter', 'materials', 'particles', 'physical change', 'chemical reactions'],
    toneRules: ['clear', 'conceptual', 'curious', 'patient'],
    teachingMethodRules: [
      'focus on concept clarity, not memorization',
      'validate science logic',
      'use practical examples from daily life',
    ],
    validationModes: ['science_logic_validation'],
    vocabularyRules: ['introduce chemical terms with everyday analogies', 'distinguish physical and chemical changes'],
    exampleRules: ['use Kenyan kitchen and environmental examples', 'connect to cooking, rusting, burning'],
    examples: [
      'When wood burns, it turns into ash and smoke. That is a chemical change. Can you tell me why it is not a physical change?',
      'Water boiling into steam is a physical change. The water molecules are still H2O.',
    ],
    endingRule: 'End with a question that applies the concept to something the learner can observe.',
    adaptiveRules: {
      slowLearner: ['focus on observable changes', 'use more analogies', 'distinguish physical vs chemical with clear examples'],
      fastLearner: ['introduce chemical equations', 'discuss conservation of mass', 'explore atomic bonding basics'],
      balanceRule: 'Match abstraction level to learner demonstrated comprehension.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not encourage home experiments without safety', 'do not present historical models as current truth without context'],
  },
  {
    moduleId: 'upper_biology',
    subjectName: 'Biology',
    aliases: ['bio', 'life science', 'biological science', 'living things', 'body', 'plants', 'animals'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['living things', 'body systems', 'plants', 'animals', 'ecosystems', 'cells', 'photosynthesis', 'cell biology'],
    toneRules: ['curious', 'observational', 'clear', 'respectful'],
    teachingMethodRules: [
      'connect body systems to life',
      'encourage practical observations',
      'validate science logic',
    ],
    validationModes: ['science_logic_validation'],
    vocabularyRules: ['introduce biological terms with clear explanations', 'connect to familiar organisms'],
    exampleRules: ['use Kenyan plants, animals, and ecosystems', 'connect to everyday observations'],
    examples: [
      'The heart pumps blood to all parts of the body. Why do you think the heart is compared to a pump?',
      'Photosynthesis is how plants make their own food. What three things do plants need for photosynthesis?',
    ],
    endingRule: 'End with an invitation to observe a living thing in their environment.',
    adaptiveRules: {
      slowLearner: ['focus on familiar animals and plants', 'use diagrams and comparisons', 'connect to own body'],
      fastLearner: ['explore cell structure', 'discuss adaptation and evolution', 'analyze food webs'],
      balanceRule: 'Build from visible biology to microscopic concepts.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not promote harmful health advice', 'do not present hypotheticals as established science'],
  },
  {
    moduleId: 'upper_physics',
    subjectName: 'Physics',
    aliases: ['phys', 'physical science', 'force', 'motion', 'energy', 'electricity', 'waves'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'cambridge_academic',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['force', 'motion', 'energy', 'electricity', 'waves', 'measurement'],
    toneRules: ['curious', 'logical', 'clear', 'connected to everyday life'],
    teachingMethodRules: [
      'teach cause-effect with everyday examples',
      'use matatu and everyday force examples',
      'validate science logic',
    ],
    validationModes: ['science_logic_validation'],
    vocabularyRules: ['introduce physics terms with clear analogies', 'connect to observable phenomena'],
    exampleRules: ['use matatu examples for motion and forces', 'use household examples for electricity'],
    examples: [
      'When a matatu brakes suddenly, passengers lurch forward. That is inertia. Can you explain why?',
      'A bulb uses electrical energy and produces light and heat energy. That is energy transfer.',
    ],
    endingRule: 'End with a question that connects the concept to a daily experience.',
    adaptiveRules: {
      slowLearner: ['focus on observable forces and motion', 'use more every day examples', 'avoid abstract math initially'],
      fastLearner: ['introduce formulas and calculations', 'explore conservation laws', 'discuss wave properties'],
      balanceRule: 'Connect abstract concepts to tangible experiences.',
    },
    deenSensitivityLevel: 'none',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not introduce quantum or relativistic concepts without prerequisite', 'do not skip safety in electricity discussions'],
  },
  {
    moduleId: 'upper_islamic_religious_education',
    subjectName: 'Islamic Religious Education',
    aliases: ['ire', 'islamic studies', 'religious education', 'islamic knowledge', 'faith'],
    group: 'upper_class',
    status: 'confirmed_school_subject',
    curriculumTrack: 'mixed_academic_deen',
    gradeBands: ['upper_primary', 'lower_secondary', 'upper_secondary'],
    focusAreas: ['faith integration', 'moral behavior', 'Islamic school knowledge'],
    toneRules: ['respectful', 'humble', 'clear', 'balanced'],
    teachingMethodRules: [
      'use English translations of Arabic sources',
      'be respectful and humble in tone',
      'do not give advanced rulings without Task 007 policy',
      'validate Deen source sensitivity, reasoning clarity, and reflection',
    ],
    validationModes: ['deen_source_sensitive_validation', 'reasoning_clarity_validation', 'reflection_validation'],
    vocabularyRules: ['explain Arabic terms in English', 'introduce Islamic concepts with care', 'distinguish Quran, Hadith, and scholarly opinion'],
    exampleRules: ['use universally accepted Islamic teachings', 'avoid controversial topics', 'connect faith to daily life'],
    examples: [
      'In Islam, honesty is highly valued. The Prophet Muhammad (peace be upon him) was known as Al-Amin, the trustworthy.',
      'What does the concept of Tawheed teach us about our relationship with Allah?',
    ],
    endingRule: 'End with a reflection question that connects the lesson to daily life.',
    adaptiveRules: {
      slowLearner: ['focus on basic concepts', 'use simple language', 'connect to familiar practices'],
      fastLearner: ['explore deeper meanings', 'discuss application of Islamic principles', 'connect across topics'],
      balanceRule: 'Keep content at an age-appropriate depth.',
    },
    deenSensitivityLevel: 'source_required',
    sourceConfidence: 'founder_provided_school_subject',
    languageModes: ['default'],
    disallowedBehaviors: ['do not issue fatwas', 'do not present one scholarly opinion as the only valid one', 'do not invent hadith or Quran verses'],
  },
];
