export const ADJUDICATION_POLICY_VERSIONS = {
  RECOVERY_CASE_ADJUDICATION_READINESS_CREATION: 'RECOVERY_CASE_ADJUDICATION_READINESS_CREATION_V1',
  RECOVERY_CASE_REVIEW_SESSION_CREATION: 'RECOVERY_CASE_REVIEW_SESSION_CREATION_V1',
  RECOVERY_CASE_EVIDENCE_BUNDLE_CREATION: 'RECOVERY_CASE_EVIDENCE_BUNDLE_CREATION_V1',
  RECOVERY_CASE_REVIEW_CHECKLIST_CREATION: 'RECOVERY_CASE_REVIEW_CHECKLIST_CREATION_V1',
  RECOVERY_CASE_CONFLICT_DECLARATION_CREATION: 'RECOVERY_CASE_CONFLICT_DECLARATION_CREATION_V1',
  RECOVERY_CASE_REVIEWER_DECISION_CREATION: 'RECOVERY_CASE_REVIEWER_DECISION_CREATION_V1',
  RECOVERY_CASE_PRIORITY_OVERRIDE_REQUEST_CREATION: 'RECOVERY_CASE_PRIORITY_OVERRIDE_REQUEST_CREATION_V1',
  RECOVERY_CASE_SECOND_REVIEW_REQUEST_CREATION: 'RECOVERY_CASE_SECOND_REVIEW_REQUEST_CREATION_V1',
  RECOVERY_CASE_CONSENSUS_CREATION: 'RECOVERY_CASE_CONSENSUS_CREATION_V1',
  RECOVERY_CASE_DISAGREEMENT_RESOLUTION_DRAFT_CREATION: 'RECOVERY_CASE_DISAGREEMENT_RESOLUTION_DRAFT_CREATION_V1',
  RECOVERY_CASE_QUEUE_DISPOSITION_CREATION: 'RECOVERY_CASE_QUEUE_DISPOSITION_CREATION_V1',
  RECOVERY_CASE_QUALITY_SAMPLE_CREATION: 'RECOVERY_CASE_QUALITY_SAMPLE_CREATION_V1',
  RECOVERY_CASE_ADJUDICATION_SUMMARY_MUTATION: 'RECOVERY_CASE_ADJUDICATION_SUMMARY_MUTATION_V1',
  RECOVERY_CASE_ADJUDICATION_AUDIT: 'RECOVERY_CASE_ADJUDICATION_AUDIT_V1',
} as const;

export const ADJUDICATION_SAFETY_POLICIES = {
  RECOVERY_CASE_ADJUDICATION_NO_LIVE_ASSIGNMENT: 'RECOVERY_CASE_ADJUDICATION_NO_LIVE_ASSIGNMENT_V1',
  RECOVERY_CASE_ADJUDICATION_NO_REVIEW_DISPATCH: 'RECOVERY_CASE_ADJUDICATION_NO_REVIEW_DISPATCH_V1',
  RECOVERY_CASE_ADJUDICATION_NO_ESCALATION_DISPATCH: 'RECOVERY_CASE_ADJUDICATION_NO_ESCALATION_DISPATCH_V1',
  RECOVERY_CASE_ADJUDICATION_NO_NOTIFICATION: 'RECOVERY_CASE_ADJUDICATION_NO_NOTIFICATION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_CALENDAR_EVENT: 'RECOVERY_CASE_ADJUDICATION_NO_CALENDAR_EVENT_V1',
  RECOVERY_CASE_ADJUDICATION_NO_PORTAL_PUBLISH: 'RECOVERY_CASE_ADJUDICATION_NO_PORTAL_PUBLISH_V1',
  RECOVERY_CASE_ADJUDICATION_NO_EXTERNAL_SYNC: 'RECOVERY_CASE_ADJUDICATION_NO_EXTERNAL_SYNC_V1',
  RECOVERY_CASE_ADJUDICATION_NO_LIVE_EXECUTION: 'RECOVERY_CASE_ADJUDICATION_NO_LIVE_EXECUTION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_LIVE_AUTHORIZATION: 'RECOVERY_CASE_ADJUDICATION_NO_LIVE_AUTHORIZATION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_LIVE_CLOSURE: 'RECOVERY_CASE_ADJUDICATION_NO_LIVE_CLOSURE_V1',
  RECOVERY_CASE_ADJUDICATION_NO_PRIORITY_MUTATION: 'RECOVERY_CASE_ADJUDICATION_NO_PRIORITY_MUTATION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_QUEUE_MUTATION: 'RECOVERY_CASE_ADJUDICATION_NO_QUEUE_MUTATION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_SCORE_MUTATION: 'RECOVERY_CASE_ADJUDICATION_NO_SCORE_MUTATION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_MASTERY_MUTATION: 'RECOVERY_CASE_ADJUDICATION_NO_MASTERY_MUTATION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_REGRADE_EXECUTION: 'RECOVERY_CASE_ADJUDICATION_NO_REGRADE_EXECUTION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_AI_DECISION: 'RECOVERY_CASE_ADJUDICATION_NO_AI_DECISION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_GENERATED_QUESTION: 'RECOVERY_CASE_ADJUDICATION_NO_GENERATED_QUESTION_V1',
  RECOVERY_CASE_ADJUDICATION_NO_OCR: 'RECOVERY_CASE_ADJUDICATION_NO_OCR_V1',
  RECOVERY_CASE_ADJUDICATION_NO_PDF: 'RECOVERY_CASE_ADJUDICATION_NO_PDF_V1',
  RECOVERY_CASE_ADJUDICATION_NO_SENSITIVE_FACTOR_USE: 'RECOVERY_CASE_ADJUDICATION_NO_SENSITIVE_FACTOR_USE_V1',
} as const;

export const ADJUDICATION_ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  teacher: [
    'createAdjudicationReadiness', 'createEvidenceBundle', 'completeChecklist',
    'declareConflict', 'actAsPrimaryReviewer', 'requestSecondReview',
    'createPriorityOverrideRequest',
  ],
  lead_teacher: [
    'actAsPrimaryReviewer', 'actAsSecondaryReviewer', 'reviewPriorityOverride',
    'createConsensus', 'createQueueDispositionDraft',
  ],
  department_head: [
    'actAsSecondaryReviewer', 'actAsGovernanceReviewer', 'createDisagreementResolution',
    'reviewOverrideRequest', 'createGovernanceBlockDisposition',
  ],
  admin: [
    'actAsGovernanceReviewer', 'createDisagreementResolution', 'approveForFutureUse',
    'inspectSchoolSummaries',
  ],
  system_job: [
    'createIntegrityDigest', 'evaluateChecklistStructure', 'calculateQualitySample',
    'refreshSummary',
  ],
  student: [],
  parent: [],
  guest: [],
  unknown: [],
};

export const ADJUDICATION_FORBIDDEN_MUTATION_ROLES: readonly string[] = [
  'student', 'parent', 'guest', 'unknown',
];

export const ADJUDICATION_REQUIRES_SECOND_REVIEW: readonly string[] = [
  'critical_review',
];

export function isRoleAllowedForMutation(role: string): boolean {
  return !ADJUDICATION_FORBIDDEN_MUTATION_ROLES.includes(role);
}

export function isRoleAllowedForAction(role: string, action: string): boolean {
  const permissions = ADJUDICATION_ROLE_PERMISSIONS[role];
  if (!permissions) return false;
  return permissions.includes(action);
}

export function requiresSecondReview(priorityBand: string): boolean {
  return ADJUDICATION_REQUIRES_SECOND_REVIEW.includes(priorityBand);
}
