#!/usr/bin/env node
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import crypto from 'node:crypto';
import { getRepositoryRoot, getRuntimeDir, getCurrentHead, ensureDir, writeJSON, readJSON } from './agent-control-lib/repository.mjs';

function requireTaskId(args) {
  const idx = args.indexOf('--task');
  if (idx < 0) throw new Error('--task <task-id> required');
  return args[idx + 1];
}

function validateCommit(taskId) {
  const root = getRepositoryRoot();
  const runtimeDir = getRuntimeDir(taskId);
  const errors = [];

  const receiptPath = resolve(runtimeDir, 'staging', 'staging-receipt.json');
  if (!existsSync(receiptPath)) {
    return { valid: false, errors: ['STAGING_RECEIPT_MISSING: no staging receipt found'], warnings: [] };
  }

  const receipt = readJSON(receiptPath);
  if (!receipt.stagedBy || !receipt.stagedBy.includes('task-governor.mjs')) {
    errors.push('STAGING_RECEIPT_INVALID: receipt was not generated by task-governor.mjs');
  }

  if (!receipt.indexTreeHash) {
    errors.push('STAGING_RECEIPT_INVALID: missing indexTreeHash');
  }

  if (receipt.createdAt) {
    const commitTime = execSync('git log --format=%ct -1 HEAD', { cwd: root, encoding: 'utf-8', timeout: 5000 }).trim();
    const receiptTime = new Date(receipt.createdAt).getTime();
    if (receiptTime > commitTime * 1000) {
      errors.push('RECEIPT_CREATED_AFTER_COMMIT');
    }
  }

  if (!receipt.preCommitHead) {
    errors.push('STAGING_RECEIPT_INVALID: missing preCommitHead');
  } else {
    const commitParent = execSync('git log --format=%P -1 HEAD', { cwd: root, encoding: 'utf-8', timeout: 5000 }).trim();
    const parents = commitParent.split(' ').map(p => p.trim()).filter(p => p);
    if (!parents.includes(receipt.preCommitHead)) {
      errors.push('COMMIT_PARENT_MISMATCH: HEAD parent does not match receipt preCommitHead');
    }
    const isAmend = execSync('git rev-list --count --all --objects HEAD', { cwd: root, encoding: 'utf-8', timeout: 5000 }).trim();
  }

  const lockPath = resolve(runtimeDir, 'task-manifest.lock.json');
  if (existsSync(lockPath)) {
    const lock = readJSON(lockPath);
    const manifestPath = resolve(runtimeDir, 'task-manifest.json');
    if (existsSync(manifestPath)) {
      const manifestContent = readFileSync(manifestPath, 'utf-8');
      const computedHash = crypto.createHash('sha256').update(manifestContent).digest('hex');
      if (computedHash !== lock.manifestHash) {
        errors.push('MANIFEST_HASH_CHANGED: manifest hash does not match lock');
      }
    }
  }

  const currentHead = getCurrentHead();

  const commitFiles = execSync('git show --name-status --format="" HEAD', { cwd: root, encoding: 'utf-8' }).trim();
  const commitLines = commitFiles.split('\n').filter(l => l.trim());

  if (commitLines.length === 0 && receipt.stagedPaths && receipt.stagedPaths.length > 0) {
    const stagedFiles = execSync('git diff --cached --name-status', { cwd: root, encoding: 'utf-8' }).trim();
    const stagedLines = stagedFiles.split('\n').filter(l => l.trim());
    for (const line of stagedLines) {
      const status = line.charAt(0);
      const path = line.slice(2).trim();
      if (receipt.stagedPaths && !receipt.stagedPaths.includes(path)) {
        errors.push(`UNSTAGED_PATH_IN_COMMIT: ${path} not in staging receipt`);
      }
    }
  } else {
    for (const line of commitLines) {
      const status = line.charAt(0);
      const path = line.slice(2).trim();
      if (path && receipt.stagedPaths && !receipt.stagedPaths.includes(path)) {
        errors.push(`UNEXPECTED_PATH_IN_COMMIT: ${path} not in staging receipt`);
      }
    }
    for (const expected of (receipt.stagedPaths || [])) {
      const found = commitLines.some(l => l.slice(2).trim() === expected);
      if (!found) {
        errors.push(`MISSING_PATH_IN_COMMIT: ${expected} not found in last commit`);
      }
    }
  }

  const commitMessage = execSync('git log --format=%s -1 HEAD', { cwd: root, encoding: 'utf-8' }).trim();

  const verification = {
    taskId,
    verifiedAt: new Date().toISOString(),
    head: currentHead,
    commitMessage,
    commitFileCount: commitLines.length,
    receiptPathCount: receipt.stagedPaths?.length || 0,
    receiptIndexHash: receipt.indexTreeHash,
    errors,
    passed: errors.length === 0,
  };

  writeJSON(resolve(runtimeDir, 'commits', 'commit-verification.json'), verification);

  if (errors.length > 0) {
    errors.forEach(e => console.error(`ERROR: ${e}`));
  }
  console.log(`Commit hash: ${currentHead}`);
  console.log(`Message: ${commitMessage}`);
  console.log(`Files in commit: ${commitLines.length}`);
  console.log(`Receipt paths: ${receipt.stagedPaths?.length || 0}`);
  console.log(`Valid: ${verification.passed}`);

  return verification;
}

function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === 'validate') {
    const taskId = requireTaskId(args);
    const result = validateCommit(taskId);
    process.exit(result.passed ? 0 : 1);
  } else {
    console.error('Usage: node scripts/commit-guard.mjs validate --task <task-id>');
    process.exit(1);
  }
}

main();
