// export const VOICE_CONFIG = {
//   MAX_AUDIO_SECONDS: 15,
//   MAX_REQUESTS_PER_MINUTE: 10,
//   STREAM_CHUNK_SIZE: 4096,
//   CACHE_ENABLED: true,
//   CACHE_MAX_ITEMS: 500,
//   SELF_HOSTED_ENABLED: false, 
//   DEFAULT_TTS_SPEED: 1.0,
//   CALM_TTS_SPEED: 0.85,
//   ARABIC_TTS_SPEED: 0.9,
// };